### ISSUE TITLE
JNI DETECTED ERROR IN APPLICATION: thread

### ISSUE THREAD

**Issue by xiaoxiayu** [android-hacker/VAExposed#1027]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
下载 https://github.com/android-hacker/VirtualXposed/archive/refs/tags/0.20.3.zip 后自己编出APK 运行游戏会出现错误：

JNI DETECTED ERROR IN APPLICATION: thread Thread[1,tid=8971,Native,Thread*=0x7485a14c00,peer=0x749a3c78,"main"] using JNIEnv* from thread Thread[42,tid=9194,Runnable,Thread*=0x7479cec000,peer=0x138c09f0,"UnityMain"]
/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]     in call to NewStringUTF
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]     from void com.harry.engine.AndroidUtils.GameLogicTickInBackground()
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542] "main" prio=5 tid=1 Runnable
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   | group="main" sCount=0 dsCount=0 flags=0 obj=0x749a3c78 self=0x7485a14c00
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   | sysTid=8971 nice=0 cgrp=default sched=0/0 handle=0x750c033548
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   | state=R schedstat=( 2281341449 165011571 1556 ) utm=198 stm=29 core=1 HZ=100
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   | stack=0x7ff0b81000-0x7ff0b83000 stackSize=8MB
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   | held mutexes= "mutator lock"(shared held)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #00 pc 00000000003c19b0  /system/lib64/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+220)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #01 pc 000000000048f3bc  /system/lib64/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+352)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #02 pc 00000000002e4bb8  /system/lib64/libart.so (art::JavaVMExt::JniAbort(char const*, char const*)+968)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #03 pc 00000000002e4fc8  /system/lib64/libart.so (art::JavaVMExt::JniAbortV(char const*, char const*, std::__va_list)+116)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #04 pc 00000000000fcffc  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::AbortF(char const*, ...)+148)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #05 pc 00000000000fb6f8  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::CheckPossibleHeapValue(art::ScopedObjectAccess&, char, art::(anonymous namespace)::JniValueType)+416)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #06 pc 00000000000fad44  /system/lib64/libart.so (art::(anonymous namespace)::ScopedCheck::Check(art::ScopedObjectAccess&, bool, char const*, art::(anonymous namespace)::JniValueType*)+628)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #07 pc 00000000000f0bd0  /system/lib64/libart.so (art::(anonymous namespace)::CheckJNI::NewStringUTF(_JNIEnv*, char const*)+692)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   native: #08 pc 0000000000045fdc  /data/app/com.lilithgames.rok.offical.cn-_chAgog1IqkQOUaFGuiLJA==/lib/arm64/libEngineDll.so (???)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at com.harry.engine.AndroidUtils.GameLogicTickInBackground(Native method)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at com.harry.engine.MyUnityPlayerActivity$2.handleMessage(MyUnityPlayerActivity.java:104)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   - locked <0x01f35872> (a com.harry.engine.MyRelativeLayout)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at android.os.Handler.dispatchMessage(Handler.java:106)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at android.os.Looper.loop(Looper.java:193)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at android.app.ActivityThread.main(ActivityThread.java:7009)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at java.lang.reflect.Method.invoke(Native method)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
2021-07-29 01:22:32.868 8971-8971/com.lilithgames.rok.offical.cn A/orpion.bit64:p: java_vm_ext.cc:542]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

直接下载 https://github.com/android-hacker/VirtualXposed/releases/download/0.20.3/VirtualXposed_0.20.3.apk 运行游戏不会出现这个问题.

请问是和编译的配置或者环境有关吗？

## 复现步骤
1. 下载游戏万国觉醒，在自己编译的 VirtualXposed 中运行。
2. 在游戏加载时就可以重现错误。

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：OnPlus 7 Pro, Android 9
ROM版本：Oxygen OS 9.5.7.GM21AA
Xposed 插件以及插件版本：0.20.3.zip
VirtualXposed版本：0.20.3.zip
Android NDK: android-ndk-r21d

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
编译 Release 模式运行
