### ISSUE TITLE
0.22.0无法打开xposed installer，无法管理模块

### ISSUE THREAD

**Issue by lsh1215225** [android-hacker/VAExposed#1111]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

无法打开xposed installer，无法管理模块

## 复现步骤

每次

## 环境

机型：
机型：坚果R2
系统版本：Android11
ROM版本：8.5.2
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

## 补充

能正常安装其他app

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by xtexx** [comment]
cc @tiann

**Comment by xtexx** [comment]
一份堆栈，VXP安装了QQ和Scoop，无法打开Xposed Installer，此堆栈由实体机的Scoop通过READ_LOGS捕获。

```
FATAL EXCEPTION: main
Process: de.robv.android.xposed.installer, PID: 9513
java.lang.RuntimeException: Unable to start activity ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean android.content.pm.ApplicationInfo.enabled' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3554)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3738)
	at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:243)
	at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:225)
	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
	at android.os.Handler.dispatchMessage(Handler.java:112)
	at android.os.Looper.loop(Looper.java:216)
	at android.app.ActivityThread.main(ActivityThread.java:7779)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean android.content.pm.ApplicationInfo.enabled' on a null object reference
	at de.robv.android.xposed.installer.util.ModuleUtil.reloadInstalledModules(ModuleUtil.java:87)
	at de.robv.android.xposed.installer.util.ModuleUtil.getInstance(ModuleUtil.java:56)
	at de.robv.android.xposed.installer.WelcomeActivity.onCreate(WelcomeActivity.java:107)
	at android.app.Activity.performCreate(Activity.java:7458)
	at android.app.Activity.performCreate(Activity.java:7448)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
	at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244)
	at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:99)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3533)
	... 13 more
```

**Comment by bikekoala** [comment]
+1

**Comment by haoshuai19** [comment]
+1  一加9（LE2110，android12）

**Comment by AzraelWarrior** [comment]
+1

**环境**
机型：
机型：Redmi K40
系统版本：Android12
ROM版本：MIUI 13.0.6
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by zmorningstart** [comment]
+1

环境
机型：
机型：小米11 ultrl
系统版本：Android12
ROM版本：MIUI 13.0.12
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by bansonsour** [comment]
这问题有解决吗？

**Comment by bansonsour** [comment]
@tiann 这个问题怎么解决？

**Comment by chn-yang** [comment]
+1， 也没办法打开virtual xposed里面的app

环境
机型：
机型：redimi k40s
系统版本：Android12
ROM版本：MIUI 13.0.10
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by svchord** [comment]
+1

## 环境

机型：Realme GT Neo 3
系统版本：Android 12
ROM版本：RealmeUI 3.0
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by xtexChooser** [comment]
cc @tiann

**Comment by gause555** [comment]
+1
机型：三星NOTE 10+
系统版本：Android 12
ROM版本：ONE UI 4.1
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by superAndroidMan** [comment]
+1
机型：小米10
系统版本：Android12
ROM版本：MIUI 13.0.10
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by uestccokey** [comment]
+1
机型：华为Mate30 5G
Xposed 插件以及插件版本：自带版本
VirtualXposed版本：0.22.0

**Comment by shenkenan** [comment]
机型版本：荣耀
机型版本：荣耀10
系统版本：鸿蒙2.0
Xposed 以及插件版本：自带
VirtualXposed版本：0​​.22.0

**Comment by colarking** [comment]
+1
机型版本：Redmi Note 8 Pro
系统版本：MIUI 12.5.6
Xposed 以及插件版本：自带
VirtualXposed版本：0​​.22.0

**Comment by shenkenan** [comment]
我 收 到   了 ！！！

**Comment by solomanhl** [comment]
同样的问题，0.22+小米6

**Comment by shenkenan** [comment]
我 收 到   了 ！！！

**Comment by bbajie** [comment]
编译后也是上面问题，有修复方案吗

**Comment by shenkenan** [comment]
我 收 到   了 ！！！

**Comment by svchord** [comment]
>    我 收 到   了 ！！！

你是作者吗？

**Comment by wabisabi07** [comment]
我也打不开xposed installer

**Comment by shenkenan** [comment]
我 收 到   了 ！！！

**Comment by wabisabi07** [comment]
shenkenan ***@***.***> 于 2023年3月19日周日 15:35写道：

**Comment by Bertlk** [comment]
> 一份堆栈，VXP安装了QQ和Scoop，无法打开Xposed Installer，此堆栈由实体机的Scoop通过READ_LOGS捕获。
> 
> ```
> FATAL EXCEPTION: main
> Process: de.robv.android.xposed.installer, PID: 9513
> java.lang.RuntimeException: Unable to start activity ComponentInfo{de.robv.android.xposed.installer/de.robv.android.xposed.installer.WelcomeActivity}: java.lang.NullPointerException: Attempt to read from field 'boolean android.content.pm.ApplicationInfo.enabled' on a null object reference
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3554)
> 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3738)
> 	at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:243)
> 	at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:225)
> 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2226)
> 	at android.os.Handler.dispatchMessage(Handler.java:112)
> 	at android.os.Looper.loop(Looper.java:216)
> 	at android.app.ActivityThread.main(ActivityThread.java:7779)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:990)
> Caused by: java.lang.NullPointerException: Attempt to read from field 'boolean android.content.pm.ApplicationInfo.enabled' on a null object reference
> 	at de.robv.android.xposed.installer.util.ModuleUtil.reloadInstalledModules(ModuleUtil.java:87)
> 	at de.robv.android.xposed.installer.util.ModuleUtil.getInstance(ModuleUtil.java:56)
> 	at de.robv.android.xposed.installer.WelcomeActivity.onCreate(WelcomeActivity.java:107)
> 	at android.app.Activity.performCreate(Activity.java:7458)
> 	at android.app.Activity.performCreate(Activity.java:7448)
> 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1286)
> 	at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244)
> 	at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:99)
> 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3533)
> 	... 13 more
> ```

**Comment by shenkenan** [comment]
我 收 到   了 ！！！

**Comment by HooieRay** [comment]
i resolved this problem by degrading version to 0.20.3

**Comment by shenkenan** [comment]
我 收 到   了 ！！！

**Comment by zaoan660** [comment]
我降级到0.20.3后打不开学习通,但是其他应用有的可以打开.我记得以前能打开,学习通更新到现在的6.3.0就打不开了

**Comment by shenkenan** [comment]
我 收 到   了 ！！！
