### ISSUE TITLE
安装在雷电模拟器会闪退

### ISSUE THREAD

**Issue by lisongting** [android-hacker/VAExposed#1132]
## 问题描述
雷电模拟器安装会闪退
日志堆栈

09-04 17:50:34.159  1371  1591 I ActivityManager: Start proc 5442:io.va.exposed/u0a40 for activity io.va.exposed/io.virtualapp.splash.SplashActivity
09-04 17:50:34.181  5442  5442 D libnativebridge: call UnloadNativeBridge! state=1
09-04 17:50:34.196  1771  1771 W ContextImpl: Calling a method in the system process without a qualified user: android.app.ContextImpl.startService:1358 android.content.ContextWrapper.startService:613 android.content.ContextWrapper.startService:613 com.android.coreservice.CoreBroadcastReceiver.onReceive:53 android.app.ActivityThread.handleReceiver:3073 
09-04 17:50:34.235  1818  1945 D EGL_adreno: eglMakeCurrent: 0xb6e9b3c0: ver 3 1 (tinfo 0xc787c070)
09-04 17:50:34.268  5442  5442 W System  : ClassLoader referenced unknown path: /data/app/io.va.exposed-1/lib/x86
09-04 17:50:34.272  5442  5442 E NativeEngine: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/io.va.exposed-1/base.apk"],nativeLibraryDirectories=[/data/app/io.va.exposed-1/lib/x86, /system/lib, /vendor/lib]]] couldn't find "libva++.so"
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1002)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at java.lang.System.loadLibrary(System.java:1579)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at com.lody.virtual.client.NativeEngine.<clinit>(NativeEngine.java:40)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at com.lody.virtual.client.NativeEngine.disableJit(Native Method)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at io.virtualapp.XApp.attachBaseContext(XApp.java:33)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.Application.attach(Application.java:189)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.os.Looper.loop(Looper.java:154)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at android.app.ActivityThread.main(ActivityThread.java:6190)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
09-04 17:50:34.272  5442  5442 E NativeEngine: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
09-04 17:50:34.273  5442  5442 E art     : No implementation found for void com.lody.virtual.client.NativeEngine.disableJit(int) (tried Java_com_lody_virtual_client_NativeEngine_disableJit and Java_com_lody_virtual_client_NativeEngine_disableJit__I)
09-04 17:50:34.273  5442  5442 D AndroidRuntime: Shutting down VM
09-04 17:50:34.273  5442  5442 E AndroidRuntime: FATAL EXCEPTION: main
09-04 17:50:34.273  5442  5442 E AndroidRuntime: Process: io.va.exposed, PID: 5442
09-04 17:50:34.273  5442  5442 E AndroidRuntime: java.lang.UnsatisfiedLinkError: No implementation found for void com.lody.virtual.client.NativeEngine.disableJit(int) (tried Java_com_lody_virtual_client_NativeEngine_disableJit and Java_com_lody_virtual_client_NativeEngine_disableJit__I)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at com.lody.virtual.client.NativeEngine.disableJit(Native Method)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at io.virtualapp.XApp.attachBaseContext(XApp.java:33)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.Application.attach(Application.java:189)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:1008)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5448)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1550)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:154)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6190)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:892)
09-04 17:50:34.273  5442  5442 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:782)
09-04 17:50:34.285  1371  1592 W ActivityManager:   Force finishing activity io.va.exposed/io.virtualapp.splash.SplashActivity
09-04 17:50:34.287  1371  1386 W System.err: java.lang.Exception: show AlertDialog! title=VirtualXposed已停止运行
09-04 17:50:34.288  1371  1386 W System.err: 	at android.app.AlertDialog.show(AlertDialog.java:134)
09-04 17:50:34.288  1371  1386 W System.err: 	at com.android.server.am.AppErrors.handleShowAppErrorUi(AppErrors.java:719)
09-04 17:50:34.288  1371  1386 W System.err: 	at com.android.server.am.ActivityManagerService$UiHandler.handleMessage(ActivityManagerService.java:1637)
09-04 17:50:34.288  1371  1386 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
09-04 17:50:34.288  1371  1386 W System.err: 	at android.os.Looper.loop(Looper.java:154)
09-04 17:50:34.288  1371  1386 W System.err: 	at android.os.HandlerThread.run(HandlerThread.java:61)
09-04 17:50:34.288  1371  1386 W System.err: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)

## 复现步骤

使用雷电模拟器，安装最新apk，打开闪退

## 环境
机型：雷电模拟器
系统版本：安卓7.1.2
ROM版本：安卓7.1.2
Xposed 插件以及插件版本：未安装
VirtualXposed版本：0.22.0

![image](https://user-images.githubusercontent.com/19706962/188307928-1fdf0ab2-49ab-485d-b42f-6fb71152c3c3.png)

**Comment by pengalamangulo** [comment]
I'm fine...,father/and mam...,

Pada tanggal Min, 4 Sep 2022 16.58, LST ***@***.***> menulis:

**Comment by zaoan660** [comment]
雷电模拟器9可以打开，只是打开后不能添加软件，应该是模拟器的问题，我的旧手机可以用
