### ISSUE TITLE
Crashing on startup on Android 13

### ISSUE THREAD

**Issue by Fevirre** [android-hacker/VAExposed#1147]
Title says it all, stinks that I can't downgrade back to android 12

**Comment by welpdx** [comment]
Ditto. 
For pixel 7 android 13

**Comment by terminal-cs** [comment]
Same here, plz update developers

**Comment by kwilkins9** [comment]
Same. Note20 ultra, snapdragon.  Android 13

**Comment by lucscamps** [comment]
🤷

**Comment by didiaodanding** [comment]
您好，您的邮件已收到，谢谢。                                    --------李峰

**Comment by newcodor** [comment]
环境:
Redmi 12 Turbo
Android 13
VirtualApp Version:0.22.0
报错信息:
java.lang.RuntimeException: Unable to get provider com.google.android.apps.nexuslauncher.search.AppSearchProvider: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.ContentProviderClient.call(java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
        at android.app.ActivityThread.installProvider(ActivityThread.java:7913)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:7419)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7147)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2224)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:211)
        at android.os.Looper.loop(Looper.java:300)
        at android.app.ActivityThread.main(ActivityThread.java:8337)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.ContentProviderClient.call(java.lang.String, java.lang.String, android.os.Bundle)' on a null object reference
        at com.lody.virtual.helper.compat.ContentProviderCompat.call(ContentProviderCompat.java:24)
        at com.lody.virtual.client.ipc.ProviderCall.call(ProviderCall.java:25)
        at com.lody.virtual.client.ipc.ProviderCall$Builder.call(ProviderCall.java:75)
        at com.lody.virtual.client.ipc.ServiceManagerNative.getServiceFetcher(ServiceManagerNative.java:40)
        at com.lody.virtual.client.ipc.ServiceManagerNative.getService(ServiceManagerNative.java:77)
        at com.lody.virtual.os.VUserManager.get(VUserManager.java:113)
        at com.android.launcher3.compat.UserManagerCompatVA.<init>(UserManagerCompatVA.java:21)
        at com.android.launcher3.compat.UserManagerCompat.getInstance(UserManagerCompat.java:45)
        at com.android.launcher3.IconCache.<init>(IconCache.java:112)
        at com.android.launcher3.LauncherAppState.<init>(LauncherAppState.java:99)
        at com.android.launcher3.LauncherAppState.getInstance(LauncherAppState.java:60)
        at com.google.android.apps.nexuslauncher.search.AppSearchProvider.onCreate(AppSearchProvider.java:140)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7908)
        ... 11 more

**Comment by jakariyaa** [comment]
https://bin.kv2.dev/~654bf1535de7ed6bfdba2012

**Comment by EbanNox** [comment]
Will there be support for android 13?
