### ISSUE TITLE
virtualXpose 无法启动

### ISSUE THREAD

**Issue by s13382570** [android-hacker/VAExposed#1180]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

我下载了最新版本的virtualXpose，安装到手机上后，打开就闪退了

## 复现步骤

目前是必现，只要安装后启动就会闪退

## 环境

机型：小米civi
系统版本：
ROM版本：小米澎湃1.0.2.0  android版本 android 13
Xposed 插件以及插件版本：还未安装
VirtualXposed版本：0.22.0

## 补充
在android studio连接手机时，我看到了错误日志，希望对您有帮助：
 E  FATAL EXCEPTION: main
                                                                                                    Process: io.va.exposed:x, PID: 15508
                                                                                                    java.lang.RuntimeException: Unable to get provider com.lody.virtual.server.BinderProvider: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8079)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7585)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7313)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8503)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
                                                                                                    Caused by: java.lang.ClassCastException: java.lang.Long cannot be cast to java.lang.Integer
                                                                                                    	at com.lody.virtual.client.hook.proxies.pm.MethodProxies$GetPackageInfo.call(MethodProxies.java:635)
                                                                                                    	at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy6.getPackageInfo(Unknown Source)
                                                                                                    	at android.content.pm.PackageManager.getPackageInfoAsUserUncached(PackageManager.java:10523)
                                                                                                    	at android.content.pm.PackageManager.-$$Nest$smgetPackageInfoAsUserUncached(Unknown Source:0)
                                                                                                    	at android.content.pm.PackageManager$2.recompute(PackageManager.java:10536)
                                                                                                    	at android.content.pm.PackageManager$2.recompute(PackageManager.java:10533)
                                                                                                    	at android.app.PropertyInvalidatedCache.query(PropertyInvalidatedCache.java:939)
                                                                                                    	at android.content.pm.PackageManager.getPackageInfoAsUserCached(PackageManager.java:10550)
                                                                                                    	at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:249)
                                                                                                    	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:214)
                                                                                                    	at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:208)
                                                                                                    	at com.lody.virtual.server.am.VActivityManagerService.onCreate(VActivityManagerService.java:116)
                                                                                                    	at com.lody.virtual.server.am.VActivityManagerService.systemReady(VActivityManagerService.java:98)
                                                                                                    	at com.lody.virtual.server.BinderProvider.onCreate(BinderProvider.java:46)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2468)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2433)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8074)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7585) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7313) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2252) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211) 
                                                                                                    	at android.os.Looper.loop(Looper.java:300) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8503) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

**Comment by apex-cmyk** [comment]
这个我估计没有什么人碰到过了，要不你可以到亚矩阵云手机平台上去租个云手机玩儿试试。反正什么应用都可以安装，还是很爽的。

**Comment by didiaodanding** [comment]
您好，您的邮件已收到，谢谢。                                    --------李峰
