### ISSUE TITLE
连接WIFI情况下应用闪退

### ISSUE THREAD

**Issue by meta2** [android-hacker/VAExposed#227]
最新版本在连接WIFI的情况下会闪退，断开网络没有影响。
之前版本运行会跳出版本更新的页面，点击“更新”或者“取消”之后直接闪退；
最新版本在连网情况下打开直接闪退；
应该是版本更新这块逻辑有点问题。

**Comment by tiann** [comment]
请说明具体情况。新版没有改动这逻辑。

**Comment by meta2** [comment]
06-11 21:18:14.126 14405-14405/? I/art: Late-enabling -Xcheck:jni
06-11 21:18:14.167 14405-14405/? D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@26866f6e,provider,holder.Provider:android.content.ContentProviderProxy@3a45260f
06-11 21:18:15.105 14405-14405/io.va.exposed:x E/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
                                                             at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
                                                             at com.example.administrator.hookdebug.Main.handleLoadPackage(Main.java:57)
                                                             at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
                                                             at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
                                                             at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
                                                             at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
                                                             at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:182)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554)
                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                             at android.os.Looper.loop(Looper.java:194)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
                                                          Caused by: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
                                                             at java.lang.Class.classForName(Native Method)
                                                             at java.lang.Class.forName(Class.java:309)
                                                             at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
                                                             at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
                                                             at com.example.administrator.hookdebug.Main.handleLoadPackage(Main.java:57) 
                                                             at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
                                                             at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
                                                             at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
                                                             at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340) 
                                                             at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:182) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                             at android.os.Looper.loop(Looper.java:194) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
                                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.pm.PackageManagerService" on path: DexPathList[[zip file "/data/app/io.va.exposed-2/base.apk", zip file "/data/app/io.va.exposed-2/split_lib_dependencies_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_0_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_1_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_2_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_3_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_4_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_5_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_6_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_7_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_8_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.va.exposed-2/lib/arm, /vendor/lib, /system/lib]]
                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                             at java.lang.Class.classForName(Native Method) 
                                                             at java.lang.Class.forName(Class.java:309) 
                                                             at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823) 
                                                             at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69) 
                                                             at com.example.administrator.hookdebug.Main.handleLoadPackage(Main.java:57) 
                                                             at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
                                                             at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
                                                             at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
                                                             at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340) 
                                                             at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:182) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                             at android.os.Looper.loop(Looper.java:194) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
                                                         	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.pm.PackageManagerService" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                             		... 22 more
                                                         		Suppressed: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
                                                             at java.lang.Class.classForName(Native Method)
                                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                             			... 23 more
                                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
06-11 21:18:15.116 14405-14405/io.va.exposed:x D/Proxy: setHttpRequestCheckHandler
06-11 21:18:15.544 14405-14405/io.va.exposed:x D/ActivityThread: installProvider: context.getPackageName()=io.va.exposed
06-11 21:18:16.271 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@26fa83c6 className=com.lody.virtual.client.stub.DaemonService packageName=io.va.exposed intent=null}
06-11 21:18:16.278 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Calling onStartCommand: com.lody.virtual.client.stub.DaemonService@1df49f87, flags=0, startId=1
06-11 21:18:16.282 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@332d3eb4 className=com.lody.virtual.client.stub.DaemonService$InnerService packageName=io.va.exposed intent=null}
06-11 21:18:16.283 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Calling onStartCommand: com.lody.virtual.client.stub.DaemonService$InnerService@696badd, flags=0, startId=1
06-11 21:18:16.316 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Destroying service: com.lody.virtual.client.stub.DaemonService$InnerService@696badd

**Comment by meta2** [comment]
06-11 21:18:14.126 14405-14405/? I/art: Late-enabling -Xcheck:jni
06-11 21:18:14.167 14405-14405/? D/ActivityThread: hoder:android.app.IActivityManager$ContentProviderHolder@26866f6e,provider,holder.Provider:android.content.ContentProviderProxy@3a45260f
06-11 21:18:15.105 14405-14405/io.va.exposed:x E/Xposed: de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
                                                             at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
                                                             at com.example.administrator.hookdebug.Main.handleLoadPackage(Main.java:57)
                                                             at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
                                                             at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
                                                             at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
                                                             at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134)
                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340)
                                                             at android.app.ActivityThread.handleBindApplication(<Xposed>)
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:182)
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554)
                                                             at android.os.Handler.dispatchMessage(Handler.java:111)
                                                             at android.os.Looper.loop(Looper.java:194)
                                                             at android.app.ActivityThread.main(ActivityThread.java:5682)
                                                             at java.lang.reflect.Method.invoke(Native Method)
                                                             at java.lang.reflect.Method.invoke(Method.java:372)
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963)
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758)
                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
                                                          Caused by: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
                                                             at java.lang.Class.classForName(Native Method)
                                                             at java.lang.Class.forName(Class.java:309)
                                                             at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
                                                             at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
                                                             at com.example.administrator.hookdebug.Main.handleLoadPackage(Main.java:57) 
                                                             at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
                                                             at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
                                                             at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
                                                             at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340) 
                                                             at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:182) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                             at android.os.Looper.loop(Looper.java:194) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
                                                          Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.pm.PackageManagerService" on path: DexPathList[[zip file "/data/app/io.va.exposed-2/base.apk", zip file "/data/app/io.va.exposed-2/split_lib_dependencies_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_0_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_1_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_2_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_3_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_4_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_5_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_6_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_7_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_8_apk.apk", zip file "/data/app/io.va.exposed-2/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/io.va.exposed-2/lib/arm, /vendor/lib, /system/lib]]
                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                                             at java.lang.Class.classForName(Native Method) 
                                                             at java.lang.Class.forName(Class.java:309) 
                                                             at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823) 
                                                             at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69) 
                                                             at com.example.administrator.hookdebug.Main.handleLoadPackage(Main.java:57) 
                                                             at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34) 
                                                             at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61) 
                                                             at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106) 
                                                             at de.robv.android.xposed.XposedInit$2.beforeHookedMethod(XposedInit.java:134) 
                                                             at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:340) 
                                                             at android.app.ActivityThread.handleBindApplication(<Xposed>) 
                                                             at android.app.ActivityThread.access$1500(ActivityThread.java:182) 
                                                             at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1554) 
                                                             at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                             at android.os.Looper.loop(Looper.java:194) 
                                                             at android.app.ActivityThread.main(ActivityThread.java:5682) 
                                                             at java.lang.reflect.Method.invoke(Native Method) 
                                                             at java.lang.reflect.Method.invoke(Method.java:372) 
                                                             at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:963) 
                                                             at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:758) 
                                                             at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
                                                         	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.pm.PackageManagerService" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                                             at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                             		... 22 more
                                                         		Suppressed: java.lang.ClassNotFoundException: com.android.server.pm.PackageManagerService
                                                             at java.lang.Class.classForName(Native Method)
                                                             at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                                             at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                                             at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                                             			... 23 more
                                                          Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
06-11 21:18:15.116 14405-14405/io.va.exposed:x D/Proxy: setHttpRequestCheckHandler
06-11 21:18:15.544 14405-14405/io.va.exposed:x D/ActivityThread: installProvider: context.getPackageName()=io.va.exposed
06-11 21:18:16.271 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@26fa83c6 className=com.lody.virtual.client.stub.DaemonService packageName=io.va.exposed intent=null}
06-11 21:18:16.278 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Calling onStartCommand: com.lody.virtual.client.stub.DaemonService@1df49f87, flags=0, startId=1
06-11 21:18:16.282 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Creating service: CreateServiceData{token=android.os.BinderProxy@332d3eb4 className=com.lody.virtual.client.stub.DaemonService$InnerService packageName=io.va.exposed intent=null}
06-11 21:18:16.283 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Calling onStartCommand: com.lody.virtual.client.stub.DaemonService$InnerService@696badd, flags=0, startId=1
06-11 21:18:16.316 14405-14405/io.va.exposed:x D/ActivityThread: SVC-Destroying service: com.lody.virtual.client.stub.DaemonService$InnerService@696badd

**Comment by meta2** [comment]
华为手机到启动界面后直接闪退，
三星手机到启动界面后弹出"关于后台运行:为了让VirtualXposed内部运行不会频繁被...  我拒绝  朕同意了”提示框，如何闪退。

**Comment by meta2** [comment]
NewHomeActivity类的onResume()里面注释掉update的那两行代码就解决闪退问题了
//        new Handler().postDelayed(() ->
//                VAVersionService.checkUpdate(getApplicationContext(), false), 1000);
