### ISSUE TITLE
0.11.2 Release版本使用正常，本地编译版本 微信黑屏

### ISSUE THREAD

**Issue by ShaunRain** [android-hacker/VAExposed#247]
## 问题描述

测试自己的微信 Xposed模块，https://vxposed.com/download.html 下载的 0.11.2版本，使用过程没有问题。拉了exposed分支的代码，本地编译后出现问题。
打开微信黑屏，错误log👇

>06-15 16:03:17.416 17334-17334/io.va.exposed:p1 E/VA++: processProfileingInfo: 0xe6a66611
    compileMethod: 0xe6a5ae65
06-15 16:03:17.890 17210-17222/io.va.exposed:x E/Xposed: java.lang.IllegalArgumentException: Expected receiver of type net.androidwing.hotxposeddemo.HookerDispatcher, but got net.androidwing.hotxposeddemo.HookerDispatcher
        at java.lang.reflect.Method.invoke(Native Method)
        at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
        at net.androidwing.hotxposed.HotXposed.hook(HotXposed.java:30)
        at net.androidwing.hotxposeddemo.HookUtil.handleLoadPackage(HookUtil.java:15)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
        at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:213)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
        at android.app.LoadedApk.<init>(<Xposed>)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2164)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2119)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2091)
        at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1945)
        at android.app.ContextImpl.createPackageContext(ContextImpl.java:1933)
        at android.content.ContextWrapper.createPackageContext(ContextWrapper.java:778)
        at com.lody.virtual.server.am.AttributeCache.get(AttributeCache.java:91)
        at com.lody.virtual.server.am.ActivityStack.fetchStubActivity(ActivityStack.java:524)
        at com.lody.virtual.server.am.ActivityStack.startActivityProcess(ActivityStack.java:560)
        at com.lody.virtual.server.am.ActivityStack.startActivityInNewTaskLocked(ActivityStack.java:405)
        at com.lody.virtual.server.am.ActivityStack.startActivityLocked(ActivityStack.java:369)
        at com.lody.virtual.server.am.VActivityManagerService.startActivity(VActivityManagerService.java:133)
        at com.lody.virtual.server.IActivityManager$Stub.onTransact(IActivityManager.java:270)
        at com.lody.virtual.server.am.VActivityManagerService.onTransact(VActivityManagerService.java:271)
        at android.os.Binder.execTransact(Binder.java:574)
06-15 16:03:18.084 1481-1481/? W/recents.Component: create a new LoadPlan to load thumbnail -- background
06-15 16:03:18.106 1481-1481/? W/recents.Performance: preload while task Change spend : 23
06-15 16:03:18.118 17334-17334/com.tencent.mm W/art: JIT profile information will not be recorded: profile file does not exits.
06-15 16:03:18.125 17334-17334/com.tencent.mm E/Xposed: java.lang.IllegalArgumentException: Expected receiver of type net.androidwing.hotxposeddemo.HookerDispatcher, but got net.androidwing.hotxposeddemo.HookerDispatcher
        at java.lang.reflect.Method.invoke(Native Method)
        at de.robv.android.xposed.XposedHelpers.callMethod(XposedHelpers.java:1263)
        at net.androidwing.hotxposed.HotXposed.hook(HotXposed.java:30)
        at net.androidwing.hotxposeddemo.HookUtil.handleLoadPackage(HookUtil.java:15)
        at de.robv.android.xposed.IXposedHookLoadPackage$Wrapper.handleLoadPackage(IXposedHookLoadPackage.java:34)
        at de.robv.android.xposed.callbacks.XC_LoadPackage.call(XC_LoadPackage.java:61)
        at de.robv.android.xposed.callbacks.XCallback.callAll(XCallback.java:106)
        at de.robv.android.xposed.XposedInit$5.afterHookedMethod(XposedInit.java:213)
        at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
        at android.app.LoadedApk.<init>(<Xposed>)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2164)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2119)
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2091)
        at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:1945)
        at android.app.ContextImpl.createPackageContext(ContextImpl.java:1933)
        at com.lody.virtual.client.VClientImpl.createPackageContext(VClientImpl.java:525)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:277)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:213)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:208)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:119)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:72)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6412)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
06-15 16:03:18.324 1254-17128/? W/ActivityManager: getRunningAppProcesses: caller 10138 does not hold REAL_GET_TASKS; limiting output
06-15 16:03:18.335 1254-28211/? W/ActivityManager: getRunningAppProcesses: caller 10138 does not hold REAL_GET_TASKS; limiting output
06-15 16:03:18.361 306-723/? E/MAL-RDS:  (  rds_ru_3gpp_status_ind, 1895) [RDS-E][RU][EVENT_RU_DM_3GPP_STATUS_IND] Invalid u43gpp_status:0x8 sim:0
06-15 16:03:18.363 17334-17334/com.tencent.mm E/System: java.lang.Runtime#loadLibrary(String, ClassLoader) is private and will be removed in a future Android release
06-15 16:03:18.371 17334-17334/com.tencent.mm E/System: java.lang.Runtime#loadLibrary(String, ClassLoader) is private and will be removed in a future Android release
06-15 16:03:18.376 17334-17334/com.tencent.mm E/ActivityThread: Failed to find provider info for com.tencent.mm.coolassist.debugprovider

之后一直输出👇

> 06-15 15:38:56.395 16375-16375/com.tencent.mm:push W/System.err:     at me.weishu.epic.art.method.ArtMethod.toGenericString(ArtMethod.java:318)
        at me.weishu.epic.art.Epic$MethodInfo.toString(Epic.java:211)
        at java.lang.String.valueOf(String.java:2683)
        at java.lang.StringBuilder.append(StringBuilder.java:129)
        at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:153)
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.Types.getTypeArray(Types.java:50)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:224)
        at java.lang.reflect.Method.toGenericString(Method.java:423)
        at me.weishu.epic.art.method.ArtMethod.toGenericString(ArtMethod.java:318)
        at me.weishu.epic.art.Epic$MethodInfo.toString(Epic.java:211)
        at java.lang.String.valueOf(String.java:2683)
        at java.lang.StringBuilder.append(StringBuilder.java:129)
        at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:153)
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
06-15 15:38:56.396 16375-16375/com.tencent.mm:push W/System.err:     at libcore.reflect.Types.getTypeArray(Types.java:50)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:224)
        at java.lang.reflect.Method.toGenericString(Method.java:423)
        at me.weishu.epic.art.method.ArtMethod.toGenericString(ArtMethod.java:318)
        at me.weishu.epic.art.Epic$MethodInfo.toString(Epic.java:211)
        at java.lang.String.valueOf(String.java:2683)
        at java.lang.StringBuilder.append(StringBuilder.java:129)
        at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:153)
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.Types.getTypeArray(Types.java:50)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:224)
        at java.lang.reflect.Method.toGenericString(Method.java:423)
        at me.weishu.epic.art.method.ArtMethod.toGenericString(ArtMethod.java:318)
        at me.weishu.epic.art.Epic$MethodInfo.toString(Epic.java:211)
        at java.lang.String.valueOf(String.java:2683)
        at java.lang.StringBuilder.append(StringBuilder.java:129)
        at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:153)
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65)
06-15 15:38:56.397 16375-16375/com.tencent.mm:push W/System.err:     at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.Types.getTypeArray(Types.java:50)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:224)
        at java.lang.reflect.Method.toGenericString(Method.java:423)
        at me.weishu.epic.art.method.ArtMethod.toGenericString(ArtMethod.java:318)
        at me.weishu.epic.art.Epic$MethodInfo.toString(Epic.java:211)
        at java.lang.String.valueOf(String.java:2683)
        at java.lang.StringBuilder.append(StringBuilder.java:129)
        at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:153)
        at libcore.reflect.ParameterizedTypeImpl.getRawType(ParameterizedTypeImpl.java:65)
        at libcore.reflect.ParameterizedTypeImpl.getResolvedType(ParameterizedTypeImpl.java:76)
        at libcore.reflect.ListOfTypes.resolveTypes(ListOfTypes.java:70)
        at libcore.reflect.ListOfTypes.getResolvedTypes(ListOfTypes.java:55)
        at libcore.reflect.Types.getTypeArray(Types.java:50)
        at java.lang.reflect.Method.getGenericParameterTypes(Method.java:224)
        at java.lang.reflect.Method.toGenericString(Method.java:423)
        at me.weishu.epic.art.method.ArtMethod.toGenericString(ArtMethod.java:318)
        at me.weishu.epic.art.Epic$MethodInfo.toString(Epic.java:211)
        at java.lang.String.valueOf(String.java:2683)
        at java.lang.StringBuilder.append(StringBuilder.java:129)

## 环境

机型：Meizu M6/ 红米 note2
微信版本：6.6.0
系统版本：7.0/ 5.0.1
Xposed 插件以及插件版本：
VirtualXposed版本：0.11.2

**Comment by tiann** [comment]
自己编译的 hook 受限。
