### ISSUE TITLE
最新版本编译成功，在nexuse 5x 运行，闪退报错

### ISSUE THREAD

**Issue by tsdl2018** [android-hacker/VAExposed#280]
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@291fefd rejected from java.util.concurrent.ScheduledThreadPoolExecutor@888d7f2[Shutting down, pool size = 1, active threads = 1, queued tasks = 3, completed tasks = 6]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
        at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:334)
        at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562)
        at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:664)
        at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:630)
        at com.crashlytics.android.answers.AnswersEventsHandler.executeAsync(AnswersEventsHandler.java:185)
        at com.crashlytics.android.answers.AnswersEventsHandler.processEvent(AnswersEventsHandler.java:171)
        at com.crashlytics.android.answers.AnswersEventsHandler.processEventAsync(AnswersEventsHandler.java:47)
        at com.crashlytics.android.answers.SessionAnalyticsManager.onLifecycle(SessionAnalyticsManager.java:129)
        at com.crashlytics.android.answers.AnswersLifecycleCallbacks.onActivityPaused(AnswersLifecycleCallbacks.java:37)
        at io.fabric.sdk.android.ActivityLifecycleManager$ActivityLifecycleCallbacksWrapper$1.onActivityPaused(ActivityLifecycleManager.java:121)
        at android.app.Application.dispatchActivityPaused(Application.java:225)
        at android.app.Activity.onPause(Activity.java:1675)
        at com.android.launcher3.Launcher.onPause(Launcher.java:1067)
        at android.app.Activity.performPause(Activity.java:7143)
        at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1408)
        at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:3901)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3878)
        at android.app.ActivityThread.performPauseActivity(ActivityThread.java:3852)
        at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:3826)
        at android.app.ActivityThread.-wrap15(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1601)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by tsdl2018** [comment]
麻烦作者关闭一下，已经解决了，重启手机就好了
