### ISSUE TITLE
希望支持 Xmonkey，帮看下目前问题

### ISSUE THREAD

**Issue by zhangzhao4444** [android-hacker/VAExposed#300]
XMonkey是一款基于xposed 开发的 ui自动化集成fuzz mock测试套件，在进行monkey自动化测试同时对 text，provder，gps，intent等进行hook 篡改为异常值 用于测试 待测app容错稳定性

XMonkey已在 android6、7的 xposed环境中验证通过。

下载地址：http://repo.xposed.info/module/tv.panda.test.xmonkey

## 场景描述
问题如下：
1. 获取待测app权限结果返回[]，导致gps mock 的getCellLocation 时报 无permission 

gps fuzz 是 
在handleLoadPackage中hook了 ContextWrapper.java 的attachBaseContext，在attachBaseContext里对加载的app 获取app所拥有的权限列表结果返回[]

         val pi = pm.getPackageInfo(packageName, PackageManager.GET_PERMISSIONS)
        return pi.requestedPermissions.filterIndexed { i, _ -> pi.requestedPermissionsFlags[i] and PackageInfo.REQUESTED_PERMISSION_GRANTED != 0 }
virtualxposed 中的app 没有任何权限？

2. 勾选 动态intent fuzz测试 时启动被测app 失败，貌似是vx启动app时用了intent 然后被intent fuzz所拦截，但实际正常情况 应该仅对被测app包中的 intent进行拦截。

 动态intent fuzz 是
在 handleLoadPackage中hook了被测app包的 ContextWrapper.java 的attachBaseContext，然后对android.content.Intent的getData 以及android.os.BaseBundle的getString等进行hook 并篡改

**Comment by tiann** [comment]
1, getPackageInfo 返回的信息中没有 requestedPermissionsFlags 信息；无法用这个方式判断权限；直接checkSelfPermission 即可。
2, 不要拦截intent 中带有 \_VA\_ 字样的字段。

**Comment by zhangzhao4444** [comment]
过滤_VA_  报如下错

07-05 15:02:04.050 11457-11457/? E/WebViewFactory: error instantiating provider
    java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430)
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198)
        at android.webkit.CookieManager.getInstance(CookieManager.java:39)
        at tv.panda.account.base.c.p(SourceFile:825)
        at tv.panda.account.base.c.<init>(SourceFile:148)
        at tv.panda.account.a.a(SourceFile:48)
        at com.panda.videoliveplatform.PandaApplication.s(SourceFile:202)
        at com.panda.videoliveplatform.PandaApplication.onCreate(SourceFile:148)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:225)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:176)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:366)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:213)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:208)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:119)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:72)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6646)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
     Caused by: java.lang.ClassCastException: tv.panda.test.xmonkey.attacker.ParcelableTest cannot be cast to android.util.MemoryIntArray
        at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:1774)
        at android.provider.Settings$Global.getStringForUser(Settings.java:13714)
        at android.provider.Settings$Global.getString(Settings.java:13703)
        at android.provider.Settings$Global.getInt(Settings.java:13770)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.initialize(WebViewChromiumFactoryProvider.java:49)
        at com.android.webview.chromium.WebViewChromiumFactoryProvider.<init>(WebViewChromiumFactoryProvider.java:31)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:430) 
        at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:198) 
        at android.webkit.CookieManager.getInstance(CookieManager.java:39) 
        at tv.panda.account.base.c.p(SourceFile:825) 
        at tv.panda.account.base.c.<init>(SourceFile:148) 
        at tv.panda.account.a.a(SourceFile:48) 
        at com.panda.videoliveplatform.PandaApplication.s(SourceFile:202) 
        at com.panda.videoliveplatform.PandaApplication.onCreate(SourceFile:148) 
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1032) 
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:225) 
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:176) 
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:366) 
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:213) 
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:208) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:119) 
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:72) 
        at android.os.Handler.dispatchMessage(Handler.java:98) 
        at android.os.Looper.loop(Looper.java:154) 
        at android.app.ActivityThread.main(ActivityThread.java:6646) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358) 

原生xposed中不会出现，

**Comment by zhangzhao4444** [comment]
。。。 automatically marked

**Comment by tiann** [comment]
这个是 VA 本身的问题，除非有特别的原因，我不会花时间去支持这个。
