### ISSUE TITLE
Xposed: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by coypanglei** [android-hacker/VAExposed#344]
?E/Xposed: java.lang.ClassNotFoundException: com.android.server.am.ActivityManagerService
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.Class.forName(Class.java:324)
                                               at com.rong.xposed.fakelocation.XFakeLocation$1.afterHookedMethod(Unknown Source)
                                               at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374)
                                               at android.app.ActivityThread.systemMain(<Xposed>)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at me.weishu.epic.art.method.ArtMethod.invokeInternal(ArtMethod.java:262)
                                               at me.weishu.epic.art.method.ArtMethod.invoke(ArtMethod.java:255)
                                               at me.weishu.epic.art.method.ArtMethod.ensureResolved(ArtMethod.java:371)
                                               at me.weishu.epic.art.Epic.hookMethod(Epic.java:107)
                                               at me.weishu.epic.art.Epic.hookMethod(Epic.java:88)
                                               at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:144)
                                               at me.weishu.exposed.ExposedBridge.hookMethod(ExposedBridge.java:203)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1308)
                                               at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:205)
                                               at de.robv.android.xposed.XposedBridge.hookAllMethods(XposedBridge.java:243)
                                               at com.rong.xposed.fakelocation.XFakeLocation.a(Unknown Source)
                                               at com.rong.xposed.fakelocation.XFakeLocation.initZygote(Unknown Source)
                                               at de.robv.android.xposed.ExposedHelper.callInitZygote(ExposedHelper.java:35)
                                               at me.weishu.exposed.ExposedBridge.loadModule(ExposedBridge.java:164)
                                               at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:342)
                                               at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:214)
                                               at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:209)
                                               at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:119)
                                               at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:72)
                                               at android.os.Handler.dispatchMessage(Handler.java:98)
                                               at android.os.Looper.loop(Looper.java:154)
                                               at android.app.ActivityThread.main(ActivityThread.java:5466)
                                               at java.lang.reflect.Method.invoke(Native Method)
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)
                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
                                            Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.server.am.ActivityManagerService" on path: DexPathList[[zip file "/data/app/io.va.exposed-2/base.apk"],nativeLibraryDirectories=[/data/app/io.va.exposed-2/lib/arm, /data/app/io.va.exposed-2/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                               at java.lang.Class.classForName(Native Method) 
                                               at java.lang.Class.forName(Class.java:324) 
                                               at com.rong.xposed.fakelocation.XFakeLocation$1.afterHookedMethod(Unknown Source) 
                                               at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:374) 
                                               at android.app.ActivityThread.systemMain(<Xposed>) 
                                               at java.lang.reflect.Method.invoke(Native Method) 
                                               at me.weishu.epic.art.method.ArtMethod.invokeInternal(ArtMethod.java:262) 
                                               at me.weishu.epic.art.method.ArtMethod.invoke(ArtMethod.java:255) 
                                               at me.weishu.epic.art.method.ArtMethod.ensureResolved(ArtMethod.java:371) 
                                               at me.weishu.epic.art.Epic.hookMethod(Epic.java:107) 
                                               at me.weishu.epic.art.Epic.hookMethod(Epic.java:88) 
                                               at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:144) 
                                               at me.weishu.exposed.ExposedBridge.hookMethod(ExposedBridge.java:203) 
                                               at java.lang.reflect.Method.invoke(Native Method) 
                                               at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1308) 
                                               at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:205) 
                                               at de.robv.android.xposed.XposedBridge.hookAllMethods(XposedBridge.java:243) 
                                               at com.rong.xposed.fakelocation.XFakeLocation.a(Unknown Source) 
                                               at com.rong.xposed.fakelocation.XFakeLocation.initZygote(Unknown Source) 
                                               at de.robv.android.xposed.ExposedHelper.callInitZygote(ExposedHelper.java:35) 
                                               at me.weishu.exposed.ExposedBridge.loadModule(ExposedBridge.java:164) 
                                               at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:342) 
                                               at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:214) 
                                               at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:209) 
                                               at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:119) 
                                               at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:72) 
                                               at android.os.Handler.dispatchMessage(Handler.java:98) 
                                               at android.os.Looper.loop(Looper.java:154) 
                                               at android.app.ActivityThread.main(ActivityThread.java:5466) 
                                               at java.lang.reflect.Method.invoke(Native Method) 
                                               at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                               at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
                                               at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107) 
                                           	Suppressed: java.lang.ClassNotFoundException: Didn't find class "com.android.server.am.ActivityManagerService" on path: DexPathList[[dex file "/data/dalvik-cache/xposed_XResourcesSuperClass.dex", dex file "/data/dalvik-cache/xposed_XTypedArraySuperClass.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
                                               at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                               		... 34 more
                                           		Suppressed: java.lang.ClassNotFoundException: com.android.server.am.ActivityManagerService
                                               at java.lang.Class.classForName(Native Method)
                                               at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
                                               at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
                                               at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
                                               			... 35 more
                                            Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available

android studio编译可以，运行也可以， 安装apk没什么问题，但只要加载xposed hook 就会打开应用失败，看log是hook出现问题

**Comment by tiann** [comment]
能说下具体步骤吗？
