### ISSUE TITLE
QQ登录后后出现崩溃

### ISSUE THREAD

**Issue by lozn00** [android-hacker/VAExposed#382]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
   versionCode=24
    BOARD=FRD
    BOOTLOADER=unknown
    TYPE=user
    matchers=[Ljava.lang.String;@f3a39ba
    ID=HUAWEIFRD-AL10
    TIME=1515637388000
    BRAND=honor
    TAG=Build
    HARDWARE=hi3650
    SERIAL=GSL0217606002572
    SUPPORTED_ABIS=[Ljava.lang.String;@4d82ae5
    NO_HOTA=false
    CPU_ABI=armeabi-v7a
    IS_DEBUGGABLE=false
    RADIO=unknown
    replacements=[Ljava.lang.String;@93d706b
    MANUFACTURER=HUAWEI
    IS_EMULATOR=false
    SUPPORTED_32_BIT_ABIS=[Ljava.lang.String;@d013e4f
    TAGS=release-keys
    CPU_ABI2=armeabi
    UNKNOWN=unknown
    PERMISSIONS_REVIEW_REQUIRED=false
    USER=test
    FINGERPRINT=honor/FRD-AL10/HWFRD:7.0/HUAWEIFRD-AL10/C00B396:user/release-keys
    HOST=wuhjk0381cna
    versionName=7.0
    PRODUCT=FRD-AL10
    DISPLAY=FRD-AL10C00B396
    HIDE_PRODUCT_INFO=false
    MODEL=FRD-AL10
    DEVICE=HWFRD
    android.app.RemoteServiceException: Bad notification posted from package io.va.exposed: Couldn't expand RemoteViews for: StatusBarNotification(pkg=io.va.exposed user=UserHandle{0} id=537057263 tag=com.tencent.mobileqq@0 key=0|io.va.exposed|537057263|com.tencent.mobileqq@0|10136: Notification(pri=0 contentView=com.tencent.mobileqq/0x7f04029b vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE))
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-11 13:11:06.710 18430-18430/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.va.exposed:x, PID: 18430
    android.app.RemoteServiceException: Bad notification posted from package io.va.exposed: Couldn't expand RemoteViews for: StatusBarNotification(pkg=io.va.exposed user=UserHandle{0} id=537057263 tag=com.tencent.mobileqq@0 key=0|io.va.exposed|537057263|com.tencent.mobileqq@0|10136: Notification(pri=0 contentView=com.tencent.mobileqq/0x7f04029b vibrate=null sound=null defaults=0x0 flags=0x0 color=0x00000000 vis=PRIVATE))
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1740)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:107)
09-11 13:11:06.751 1277-9036/? E/ReportTools: This is not beta user build
09-11 13:11:06.774 589-1173/? E/logserver: imonitor_add_dynamic_path, path:/data/system/dropbox/data_app_crash@1536642666770.txt
（请尽量详细地描述你遇到的问题）

## 复现步骤
强制让qq停止，q++停止，然后方可打开Q++(情迁红包新版本)，原因是自动运行会导致都加载的同一个so,所以得先让q++正常打开然后更新so。
这时候q++正常打开，qq也能打开，但是登录后出现了
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境
这错误里面已经说了环境，虚拟环境机型已经补充好了。

## 补充
virtualxposed版本0.51.1
（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by lozn00** [comment]
重装新版本qq无问题。
