### ISSUE TITLE
mumu模拟器1.26.1.2版本无法使用0.15.1版本VXP

### ISSUE THREAD

**Issue by xausky** [android-hacker/VAExposed#396]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

如题，mumu模拟器1.26.1.2版本是安卓4.4.4版本的最后一版模拟器，虽然现在出2.x版本了，但是因为新版本使用6.0的内核，性能下降且问题很多，我的模组管理器用户还有一部分使用1.x版本的，包括我。

我可以确定的是0.12.7版本的VXP内核可以在这个模拟器上使用。

## 复现步骤

使用模组管理器2.6.0版本：https://github.com/xausky/UnityModManager/releases/tag/v2.6.0
该版本模拟器使用0.15.1版本VXP的VA内核，只去除了自签名验证，和APK签名验证，以及去除了epic相关依赖和代码（因为只用于虚拟环境，并不运行Xposed）
运行于mumu模拟器1.26.1.2版本，启动即闪退。

一下是我猜测的使用VXP复现的方法：

修改最低sdk支持到19，编译在mumu模拟器1.26.1.2版本运行，启动并且调用getInstalledApps后崩溃。

## 环境

机型：mumu模拟器
系统版本：1.26.1.2
ROM版本：4.4.4
Xposed 插件以及插件版本：无
VirtualXposed版本：0.15.1

## 补充

以下是我的管理器输出的错误：

```
09-19 22:23:40.363 4157-4157/io.github.xausky.unitymodmanager E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.github.xausky.unitymodmanager, PID: 4157
    java.lang.RuntimeException: Unable to start activity ComponentInfo{io.github.xausky.unitymodmanager/io.github.xausky.unitymodmanager.MainActivity}: java.lang.NullPointerException
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2208)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257)
        at android.app.ActivityThread.access$900(ActivityThread.java:137)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5089)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.NullPointerException
        at com.lody.virtual.helper.compat.ContentProviderCompat.call(ContentProviderCompat.java:24)
        at com.lody.virtual.client.ipc.ProviderCall.call(ProviderCall.java:25)
        at com.lody.virtual.client.ipc.ProviderCall$Builder.call(ProviderCall.java:75)
        at com.lody.virtual.client.ipc.ServiceManagerNative.getServiceFetcher(ServiceManagerNative.java:40)
        at com.lody.virtual.client.ipc.ServiceManagerNative.getService(ServiceManagerNative.java:77)
        at com.lody.virtual.client.core.VirtualCore.getStubInterface(VirtualCore.java:279)
        at com.lody.virtual.client.core.VirtualCore.getService(VirtualCore.java:270)
        at com.lody.virtual.client.core.VirtualCore.getInstalledApps(VirtualCore.java:739)
        at io.github.xausky.unitymodmanager.adapter.AttachesAdapter.update(AttachesAdapter.java:62)
        at io.github.xausky.unitymodmanager.adapter.AttachesAdapter.<init>(AttachesAdapter.java:47)
        at io.github.xausky.unitymodmanager.fragment.AttachFragment.setBase(AttachFragment.java:44)
        at io.github.xausky.unitymodmanager.fragment.BaseFragment.initialize(BaseFragment.java:45)
        at io.github.xausky.unitymodmanager.MainActivity.onCreate(MainActivity.java:50)
        at android.app.Activity.performCreate(Activity.java:5263)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2172)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2257) 
        at android.app.ActivityThread.access$900(ActivityThread.java:137) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1202) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5089) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:792) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:608) 
        at dalvik.system.NativeStart.main(Native Method) 
```

感谢作者，辛苦了。

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by tiann** [comment]
本项目的目的并不是做双开，与Xposed功能无关的都不会修复。
