### ISSUE TITLE
框架内使用chrome会崩溃！

### ISSUE THREAD

**Issue by scucsxn** [android-hacker/VAExposed#451]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

当框架内安装含有浏览器相关APP时，运行10秒左右会崩溃

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：
ROM版本：（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by scucsxn** [comment]
org.chromium.chrome.browser

**Comment by tiann** [comment]
Chrome 装里面有啥用？

**Comment by scucsxn** [comment]
> Chrome 装里面有啥用？

或者使用了chrome的 app,就有用了，有网页的那种APP，直接安装谷歌浏览器可以更直观的看到错误，这个错误我在android5.0, 6.0, 7.0, 8.0都测试了，都有crash

E/cr_ChildProcessConn: Failed to setup connection.
    android.os.DeadObjectException
        at android.os.BinderProxy.transactNative(Native Method)
        at android.os.BinderProxy.transact(Binder.java:503)
        at org.chromium.base.process_launcher.IChildProcessService$Stub$Proxy.setupConnection(IChildProcessService.java:131)
        at org.chromium.content.browser.ChildProcessConnection.doConnectionSetup(ChildProcessConnection.java:463)
        at org.chromium.content.browser.ChildProcessConnection.access$400(ChildProcessConnection.java:2404)
        at org.chromium.content.browser.ChildProcessConnection$ChildServiceConnectionImpl$1.run(ChildProcessConnection.java:130)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
W/cr_ChildProcessConn: onServiceDisconnected (crash or killed by oom): pid=0

**Comment by scucsxn** [comment]
> Chrome 装里面有啥用？

这个问题可以解决吗

**Comment by tiann** [comment]
跟Xposed 没什么关系，不会解决。

**Comment by huangtao591** [comment]
我也碰到了这个问题，主要是启动webkit的sandbox时失败的，sandbox服务进程会启动失败，然后app尝试多次启动时造成OOM，在VA或VX外启动APP时sandbox服务会正常启动没问题。
