### ISSUE TITLE
在VitualXposed中微信小程序打不开

### ISSUE THREAD

**Issue by xfx761** [android-hacker/VAExposed#503]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
   在VitualXposed中微信小程序打不开，而且如果卸载掉VitualXposed外的微信，VitualXposed里面的微信会打不开。
## 复现步骤
    安装VitualXposed 0.16.1  -> 在VitualXposed中安装微信  ->创建桌面快捷方式 -> 卸载系统微信 ->Vitual中的微信就打不开了，提示打开com.tencent.mm 失败 ->重新在系统上安装微信->能打开vitualxposed微信了，但是小程序进不去了，点了没反应。
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：
系统版本：华为荣耀8c BKK-AL10
ROM版本： EMUI版本8.2.0
Xposed 插件以及插件版本：
VirtualXposed版本：0.16.1

## 补充
  帮忙分析一下可能的原因呗

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by xfx761** [comment]
配置跟上述一样，用virtualXposed中的微信发朋友圈也出现崩溃，崩溃信息如下：`    Process: com.tencent.mm, PID: 9266
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.tencent.mm/com.tencent.mm.plugin.sns.ui.SnsUploadUI}: android.view.InflateException: Binary XML file line #199: Binary XML file line #199: Error inflating class <unknown>
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3318)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: android.view.InflateException: Binary XML file line #199: Binary XML file line #199: Error inflating class <unknown>
     Caused by: android.view.InflateException: Binary XML file line #199: Error inflating class <unknown>
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:658)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:801)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:741)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:874)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:877)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:835)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at com.tencent.mm.ui.s.a(SourceFile:423)
        at com.tencent.mm.ui.MMActivity.onCreate(SourceFile:176)
        at com.tencent.mm.plugin.sns.ui.SnsUploadUI.onCreate(SourceFile:154)
        at android.app.Activity.performCreate(Activity.java:7343)
        at android.app.Activity.performCreate(Activity.java:7333)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1219)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:244)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:99)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3271)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3429)
        at android.app.ActivityThread.-wrap12(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2009)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
     Caused by: java.lang.SecurityException: Requesting code from com.tencent.mm to be run in process com.tencent.mm/10003
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2511)
        at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2288)
        at android.app.ContextImpl.createPackageContext(ContextImpl.java:2269)
        at android.app.ActivityThread.getContextForClassLoader(ActivityThread.java:7592)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7202)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6819)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2824)
2018-12-19 18:56:48.422 9266-9266/? E/AndroidRuntime:     at android.content.ContentResolver.acquireProvider(ContentResolver.java:1776)
        at android.content.ContentResolver.call(ContentResolver.java:1746)
        at com.tencent.mm.ca.a$b.bb(SourceFile:514)
        at com.tencent.mm.view.f.a.cLW(SourceFile:388)
        at com.tencent.mm.view.f.a.<init>(SourceFile:143)
        at com.tencent.mm.view.SmileyPanelImpl.init(SourceFile:42)
        at com.tencent.mm.view.SmileyPanelImpl.<init>(SourceFile:33)
        at com.tencent.mm.plugin.emoji.model.i$5.cX(SourceFile:339)
        at com.tencent.mm.plugin.sns.ui.SnsUploadSayFooter.<init>(SourceFile:52)
        	... 30 more`

**Comment by ythgthereal** [comment]
你在vitualXposed里面把小程序删除了，重新安装小程序，再打开试试

**Comment by zy990081568** [comment]
试下这种方法
LoadedApk  
       public static RefObject<Boolean> mSecurityViolation;

VClientImpl.bindApplicationNoCheck
        mBoundApplication.info = ContextImpl.mPackageInfo.get(context);
        LoadedApk.mSecurityViolation.set(mBoundApplication.info, false);
