### ISSUE TITLE
源码安装的Xposed安装XPrivacyLua后无法打开

### ISSUE THREAD

**Issue by 3c** [android-hacker/VAExposed#520]
## 问题描述
源码build安装后，从 https://repo.xposed.info/module/eu.faircode.xlua 下载apk，放入sd卡，然后添加进VirtualXposed ，打开 Xposed 勾选插件，之后重启。 然后就打不开Xposed了。

Xposed崩溃log：
```
01-11 18:51:23.671 11254-12246/system_process E/DatabaseUtils: Writing exception to parcel
    java.lang.IllegalArgumentException: Supported SQL:
      uri content://some_table/some_property with null where and where args
      uri content://some_table with query name=? and single name as arg
      uri content://some_table with query name=some_name and null args
      but got - uri:content://settings/system, where:null whereArgs:[de.robv.android.xposed.installer, 10001]
        at com.android.providers.settings.SettingsProvider$Arguments.<init>(SettingsProvider.java:1465)
        at com.android.providers.settings.SettingsProvider.query(SettingsProvider.java:293)
        at android.content.ContentProvider.query(ContentProvider.java:1017)
        at android.content.ContentProvider$Transport.query(ContentProvider.java:238)
        at android.content.ContentProviderNative.onTransact(ContentProviderNative.java:112)
        at android.os.Binder.execTransact(Binder.java:453)
01-11 18:51:23.671 23137-23137/de.robv.android.xposed.installer D/ProviderHook: call: query ([io.va.exposed, content://settings/system, [Ljava.lang.String;@c7a6478, null, [Ljava.lang.String;@7898751, null, null]) with error
01-11 18:51:23.672 23137-23137/de.robv.android.xposed.installer E/XLua.Xposed: java.lang.IllegalArgumentException: Supported SQL:
      uri content://some_table/some_property with null where and where args
      uri content://some_table with query name=? and single name as arg
      uri content://some_table with query name=some_name and null args
      but got - uri:content://settings/system, where:null whereArgs:[de.robv.android.xposed.installer, 10001]
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
        at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodBox.call(MethodBox.java:24)
        at com.lody.virtual.client.hook.providers.ProviderHook.query(ProviderHook.java:118)
        at com.lody.virtual.client.hook.providers.ProviderHook.invoke(ProviderHook.java:210)
        at java.lang.reflect.Proxy.invoke(Proxy.java:393)
        at $Proxy45.query(Unknown Source)
        at android.content.ContentResolver.query(ContentResolver.java:493)
        at android.content.ContentResolver.query(ContentResolver.java:435)
        at eu.faircode.xlua.XLua.hookPackage(SourceFile:276)
        at eu.faircode.xlua.XLua.access$000(SourceFile:71)
        at eu.faircode.xlua.XLua$4.afterHookedMethod(SourceFile:260)
        at de.robv.android.xposed.ExposedHelper.afterHookedMethod(ExposedHelper.java:24)
        at me.weishu.exposed.XC_MethodHookX2Dx.afterHookedMethod(XC_MethodHookX2Dx.java:25)
        at com.taobao.android.dexposed.DexposedBridge.handleHookedArtMethod(DexposedBridge.java:275)
        at me.weishu.epic.art.entry.Entry.onHookObject(Entry.java:69)
        at me.weishu.epic.art.entry.Entry.referenceBridge(Entry.java:186)
        at java.lang.reflect.Method.invoke(Native Method)
        at mirror.RefMethod.call(RefMethod.java:63)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:362)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:221)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:216)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleLaunchActivity(HCallbackStub.java:124)
        at com.lody.virtual.client.hook.proxies.am.HCallbackStub.handleMessage(HCallbackStub.java:77)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5461)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

```

重新安装后，看了一下xposed的log，感觉就没有加载成功
xposed 启动log

```
--------- beginning of main
--------- beginning of system
01-11 17:54:43.696 I/XposedInstaller(20373): null getActivityXposedVersion called.
01-11 17:54:43.726 I/DexposedBridge(20373): module:/data/user/0/com.mobjump.kidsland/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore
01-11 17:54:47.008 I/XposedInstaller(20373): Downloaded http://dl.xposed.info/repo/full.xml.gz with status 0 (error: null), size 1513501 bytes
01-11 17:54:53.547 I/XposedInstaller(20373): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 16388 (1349 new / 0 removed modules)
--------- beginning of system
--------- beginning of main
01-11 18:26:47.044 I/DexposedBridge( 4525): xposed config file exists, check version
01-11 18:26:47.046 I/DexposedBridge( 4525): xposed version keep same, continue.
01-11 18:26:47.097 I/XposedInstaller( 4525): null getActivityXposedVersion called.
01-11 18:26:47.126 I/DexposedBridge( 4525): module:/data/user/0/com.mobjump.kidsland/virtual/data/app/de.robv.android.xposed.installer/base.apk is disabled, ignore

```

## 复现步骤

（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：小米3W
系统版本：6.0.1
ROM版本：CM13
Xposed 插件以及插件版本：89
VirtualXposed版本：0.16.1

## 补充

试了一下 release page 下载的，就可以正常运行。

源码build后打开xposed的版本显示为  89 版已激活
release page的xposed版本为  91 版已激活
不知道是否和这个有关

**Comment by wangfeng35** [comment]
realse版本的安装完直接崩溃了。。
