### ISSUE TITLE
小米mix2 Unable to create service

### ISSUE THREAD

**Issue by yiwowang** [android-hacker/VAExposed#537]
## 问题描述

在VirtualXposed里打开百度App，百度App直接闪退，崩溃信息：
Process: com.baidu.searchbox, PID: 15311
    java.lang.RuntimeException: Unable to create service com.baidu.searchbox.downloads.DownloadService: java.lang.SecurityException: Permission Denial: opening provider com.baidu.searchbox.download.component.DownloadProviderProxy from ProcessRecord{e677f99 15311:io.va.exposed:p0/u0a136} (pid=15311, uid=10136) that is not exported from UID 10546
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3453)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1712)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: java.lang.SecurityException: Permission Denial: opening provider com.baidu.searchbox.download.component.DownloadProviderProxy from ProcessRecord{e677f99 15311:io.va.exposed:p0/u0a136} (pid=15311, uid=10136) that is not exported from UID 10546
        at android.os.Parcel.readException(Parcel.java:1951)
        at android.os.Parcel.readException(Parcel.java:1897)
        at android.content.IContentService$Stub$Proxy.registerContentObserver(IContentService.java:768)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
        at java.lang.reflect.Proxy.invoke(Proxy.java:913)
        at $Proxy23.registerContentObserver(Unknown Source)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1940)
        at android.content.ContentResolver.registerContentObserver(ContentResolver.java:1929)
        at com.baidu.searchbox.downloads.DownloadService.onCreate(SearchBox:373)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3443)
        at android.app.ActivityThread.-wrap4(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1712) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:176) 
        at android.app.ActivityThread.main(ActivityThread.java:6701) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783) 

机型：小米mix2
系统版本：Android8.0
ROM版本：MIUI 10.2 稳定版
Xposed 插件以及插件版本：自己写的demo插件，bug和插件本身无关
VirtualXposed版本：0.16.0

## 补充

崩溃的百度App版本：11.3.5.12

我这不急修复，只是提供一下bug信息，非常感谢维护此工具的大神们

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by yiwowang** [comment]
> This issue is closed because it does not meet our issue template/为方便解决问题，请使用 issue 模版提交问题。

我写的是基于模板修改的，问题描述已经足够了
