### ISSUE TITLE
华为p20pro Xposed Installer闪退

### ISSUE THREAD

**Issue by tangxuesong6** [android-hacker/VAExposed#545]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

华为p20pro Xposed Installer闪退。

## 复现步骤

打开VirtualXposed，接下来点击Xposed Installer，app闪退。

## 环境

机型：华为p20pro
系统版本：emui 9
ROM版本：稳定版
Xposed 插件以及插件版本：
VirtualXposed版本：最新版本

## 补充
附上错误日志：
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.robv.android.xposed.installer, PID: 16144
    de.robv.android.xposed.XposedHelpers$InvocationTargetError: java.lang.NoClassDefFoundError: me.weishu.epic.art.method.a
```
```
Caused by: java.lang.NoClassDefFoundError: me.weishu.epic.art.method.a
        at me.weishu.epic.art.method.ArtMethod.getEntryPointFromQuickCompiledCode(Unknown Source:2)
        at me.weishu.epic.art.Epic.a(Unknown Source:67)
        at me.weishu.epic.art.Epic.hookMethod(Unknown Source:4)
        at de.robv.android.xposed.DexposedBridge.hookMethod(Unknown Source:66)
        at me.weishu.exposed.ExposedBridge.hookMethod(ExposedBridge.java:342)
        at java.lang.reflect.Method.invoke(Native Method)
        at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1308)
        at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:206) 
        at me.weishu.exposed.ExposedBridge.initForXposedInstaller(ExposedBridge.java:484) 
        at me.weishu.exposed.ExposedBridge.initOnce(ExposedBridge.java:120) 
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:352) 
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:221) 
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:216) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:148) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:145) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.ExceptionInInitializerError
        at me.weishu.epic.art.method.ArtMethod.getEntryPointFromQuickCompiledCode(Unknown Source:2)
        at com.taobao.android.dexposed.utility.a.d(Unknown Source:27)
        at me.weishu.epic.art.Epic.<clinit>(Unknown Source:47)
        at me.weishu.epic.art.Epic.hookMethod(Unknown Source:0)
        at de.robv.android.xposed.DexposedBridge.hookMethod(Unknown Source:59)
        at me.weishu.exposed.ExposedBridge.hookMethod(ExposedBridge.java:342)
        at java.lang.reflect.Method.invoke(Native Method)
        at de.robv.android.xposed.XposedHelpers.callStaticMethod(XposedHelpers.java:1308)
        at de.robv.android.xposed.XposedBridge.hookMethod(XposedBridge.java:206)
        at de.robv.android.xposed.XposedHelpers.findAndHookMethod(XposedHelpers.java:187)
        at me.weishu.exposed.ExposedBridge.initForXposedInstaller(ExposedBridge.java:445)
        at me.weishu.exposed.ExposedBridge.initOnce(ExposedBridge.java:120) 
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:352) 
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:221) 
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:216) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:148) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:145) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:86) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2123) 
        at android.os.Handler.dispatchMessage(Handler.java:109) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:7470) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958) 
     Caused by: java.lang.RuntimeException: API LEVEL: 28 is not supported now : (
        at me.weishu.epic.art.method.a.<clinit>
```

**Comment by FreeDreamWings** [comment]
我的荣耀V9 EMUI9.0Android9.0，也是打开xposed installer后就闪退（vx版本0.17.1），其他在vx中的app运行正常，在0.16.1版本可以正常打开xposed installer，但在0.16.1版本中使用xprivacylua，在xposed installer中激活后就会导致其他在vx中的app无法正常打开，全部闪退，应该是android9.0兼容性问题。

**Comment by wangxiaolinwxl** [comment]
p20  也闪退
系统版本：emui 9
ROM版本：稳定版
Xposed 插件以及插件版本：
VirtualXposed版本：最新版本

**Comment by zjszzw** [comment]
一样的问题
安卓9.0－pixel experience
红米note4x

**Comment by tiann** [comment]
#544
