### ISSUE TITLE
1.7以上版本微信分身打不开

### ISSUE THREAD

**Issue by 1217965058** [android-hacker/VAExposed#551]
## 问题描述
更新1.7以上版本后，微信分身打不开。1.6时是能打开是

## 复现步骤
直接从virtualXposed里打开微信，显示opening微信，再之后停止运行(开发者选项里打开显示后台ARN)闪退

## 环境
机型：一加5
系统版本：安卓9.0
ROM版本：氢OS 9.0.1
Xposed 插件以及插件版本：没有安装插件
VirtualXposed版本：1.7.1及以上

## 补充
关掉Xposed也是打不开的
下面是logcat
--------- beginning of system
02-27 15:36:18.624  1367  2346 I Nat464Xlat: Android Xlat enabled is doXlat=true
--------- beginning of main
02-27 15:36:21.009   752  1185 E qti_sensors_hal: reportSingleEvent: prox data: 5.000305 raw:24.000000 2989042176.000000 SAM TS: 34373564 HAL TS:1044420427380 elapsedRealtimeNano:1044507214079
02-27 15:36:21.556   913   913 W thermal-engine: type=1400 audit(0.0:829): avc: denied { read } for name="u:object_r:system_prop:s0" dev="tmpfs" ino=21558 scontext=u:r:thermal-engine:s0 tcontext=u:object_r:system_prop:s0 tclass=file permissive=0
02-27 15:36:21.571   913  1024 E libc    : Access denied finding property "sys.thermal.para"
02-27 15:36:21.926  1367  4006 E LocationManagerService: removeUpdates: uid=10173, pid=4972, intent=null, package=mark.via listener android.location.ILocationListener$Stub$Proxy@7431910 intent= null
02-27 15:36:21.984   793  1243 I APM_AudioPolicyManager: isStrategyActive: strategy:0,stream:1
02-27 15:36:21.984   793  1243 I APM_AudioPolicyManager: getNewOutputDevice() selected device 2
02-27 15:36:21.988   736  3510 E voice   : voice_is_in_call:in_call 0
02-27 15:36:21.988   736  3510 E voice   : voice_is_in_call:in_call 0
02-27 15:36:21.988   736  3510 I msm8974_platform: platform_check_and_set_codec_backend_cfg:becf: afe: bitwidth 24, samplerate 48000 channels 2, backend_idx 0 u
secase = 1 device (speaker)
02-27 15:36:21.988   736  3510 I msm8974_platform: platform_check_and_set_codec_backend_cfg: new_snd_devices[0] is 2
02-27 15:36:21.988   736  3510 I msm8974_platform: platform_check_codec_backend_cfg:becf: afe: bitwidth 24, samplerate 48000 channels 2, backend_idx 0 usecase = 1 device (speaker)
02-27 15:36:21.988   736  3510 E voice   : voice_is_in_call:in_call 0
02-27 15:36:21.989   736  3510 I msm8974_platform: platform_check_codec_backend_cfg:becf: afe: Codec selected backend: 0 updated bit width: 24 and sample rate:48000
02-27 15:36:21.989   736  3510 E msm8974_platform: platform_check_backends_match: Invalid snd_device =
02-27 15:36:21.989   736  3510 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 1, with Raise=0
02-27 15:36:21.989   736  3510 I audio_hw_utils: audio_extn_utils_update_stream_output_app_type_cfg Allowing 24-bit playback on speaker ONLY at default sampling rate
02-27 15:36:21.989   736  3510 E soundtrigger: audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 3
02-27 15:36:21.990   736  3510 I audio_hw_utils: send_app_type_cfg_for_device PLAYBACK app_type 69937, acdb_dev_id 15, sample_rate 48000, snd_device_be_idx 39
02-27 15:36:21.999  1367  3588 I ActivityManager: START u0 {flg=0x10000000 cmp=io.va.exposed/io.virtualapp.home.LoadingActivity (has extras)} from uid 10324 pid 6647
02-27 15:36:22.002   603   603 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.iop@2.0::IIop/default in either framework or device manifest.
02-27 15:36:22.002  1367  3588 E ANDR-PERF-JNI: Iop tryGetService failed
02-27 15:36:22.015  6647  6647 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@d3d9d3e
02-27 15:36:22.022  6647  6647 I LoadingActivity: com.tencent.mmis running: false
02-27 15:36:22.023  6647  6647 I LoadingActivity: target package: com.tencent.mm targetSdkVersion: 26
02-27 15:36:22.023  6647  6647 I LoadingActivity: target package support runtime permission, launch directly.
02-27 15:36:22.045  1367  1415 I ActivityManager: Displayed io.va.exposed/io.virtualapp.home.LoadingActivity: +31ms (total +51s26ms)
02-27 15:36:22.120 13684 13684 I RecentsModel: onTaskStackChanged# mTaskChangeId=27
02-27 15:36:22.192   793  1243 I APM_AudioPolicyManager: stopOutput() output 13, stream 1, session 25
02-27 15:36:22.192   793  1243 I APM_AudioPolicyManager: getNewOutputDevice() selected device 0
02-27 15:36:22.850  3837 15459 I GmscoreIpa: Starting mediastore instant index
02-27 15:36:23.035 15464 15464 E o.va.exposed:p: Not starting debugger since process cannot load the jdwp agent.
02-27 15:36:23.036  1367  1402 I ActivityManager: Start proc 15464:io.va.exposed:p2/u0a324 for content provider io.va.exposed/com.lody.virtual.client.stub.StubCP$C2
02-27 15:36:23.048 15464 15476 I o.va.exposed:p: The ClassLoaderContext is a special shared library.
02-27 15:36:23.055 15464 15464 I o.va.exposed:p: The ClassLoaderContext is a special shared library.
02-27 15:36:23.072 15464 15464 I Perf    : Connecting to perf service.
02-27 15:36:23.089 15464 15464 E VA++    : processProfileingInfo: 0xf2115f3d
02-27 15:36:23.089 15464 15464 E VA++    : compileMethod: 0xf2100da9
02-27 15:36:23.092 15464 15464 I FreeReflect: runtime ptr: 0xf273c400, vmExtPtr: 0xf272c3e0
02-27 15:36:23.092 15464 15464 I FreeReflect: found offset: 360
02-27 15:36:23.092 15464 15464 I FreeReflect: offsetOfVmExt: 360
02-27 15:36:23.092 15464 15464 I FreeReflect: found offset: 796
02-27 15:36:23.092 15464 15464 I FreeReflect: target: 796
02-27 15:36:23.092 15464 15464 I FreeReflect: is_java_debuggable: 0, is_native_debuggable: 0, safe_mode: 0
02-27 15:36:23.092 15464 15464 I FreeReflect: hidden api policy before : 3
02-27 15:36:23.092 15464 15464 I FreeReflect: fingerprint: OnePlus/OnePlus5/OnePlus5:9/PKQ1.180716.001/1901211819:user/release-keys
02-27 15:36:23.092 15464 15464 I FreeReflect: hidden api policy after: 0
02-27 15:36:23.182   662  3829 W DnsTlsSocket: SSL_connect error 5, errno=110
02-27 15:36:23.182   662  3830 W DnsTlsSocket: SSL_connect error 5, errno=110
02-27 15:36:23.182  1367  2346 I Nat464Xlat: Android Xlat enabled is doXlat=true
02-27 15:36:23.182  1367  2346 I Nat464Xlat: Android Xlat enabled is doXlat=true
02-27 15:36:23.211   602   602 E SELinux : avc:  denied  { find } for service=persistent_data_block pid=15464 uid=10324 scontext=u:r:untrusted_app_25:s0:c512,c768 tcontext=u:object_r:persistent_data_block_service:s0 tclass=service_manager permissive=0
02-27 15:36:23.212 15464 15464 W MethodInvocationStub: Unable to build HookDelegate: BinderInvocationStub.
02-27 15:36:23.248 15464 15464 I TransactionHandlerStub: inject transaction handler.
02-27 15:36:23.250 15464 15464 I TransactionHandlerStub: executor's handler: android.app.TransactionHandlerProxy@7dd6cde
02-27 15:36:23.260  1367  4006 I ActivityManager: START u0 {typ=com.tencent.mm/com.tencent.mm.ui.LauncherUI flg=0x18280000 cmp=io.va.exposed/com.lody.virtual.client.stub.StubActivity$C2 (has extras)} from uid 10324 pid 15042
02-27 15:36:23.265  1367  4006 E ActivityTrigger: activityStartTrigger: not whiteListedio.va.exposed/com.lody.virtual.client.stub.StubActivity$C2/172
02-27 15:36:23.265  1367  4006 E ActivityTrigger: activityResumeTrigger: not whiteListedio.va.exposed/com.lody.virtual.client.stub.StubActivity$C2/172
02-27 15:36:23.270  1367  4006 E ActivityTrigger: activityResumeTrigger: not whiteListedio.va.exposed/com.lody.virtual.client.stub.StubActivity$C2/172
02-27 15:36:23.287 15464 15464 I CrashlyticsCore: Initializing Crashlytics 2.6.0.22
02-27 15:36:23.299   603   603 W hwservicemanager: getTransport: Cannot find entry vendor.qti.hardware.iop@2.0::IIop/default in either framework or device manifest.
02-27 15:36:23.301 15464 15464 I TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@7355c97
02-27 15:36:23.301 15464 15464 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@7355c97
02-27 15:36:23.301 15464 15464 I TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@7355c97
02-27 15:36:23.301 15464 15464 I TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@7355c97
02-27 15:36:23.310 15464 15464 I VClientImpl: Binding application com.tencent.mm, (com.tencent.mm)
02-27 15:36:23.321 15464 15464 W VClientImpl: Xposed is disable..
02-27 15:36:23.322 15464 15464 I o.va.exposed:p: The ClassLoaderContext is a special shared library.
02-27 15:36:23.326 15464 15464 W o.va.exposed:p: ClassLoaderContext classpath size mismatch for position 0. expected=0, found=1 (PCL[] | PCL[/system/framework/org.apache.http.legacy.boot.jar*2011144328])
02-27 15:36:23.369 15464 15464 W o.va.exposed:p: ClassLoaderContext classpath size mismatch for position 0. expected=0, found=13 (PCL[] | PCL[/system/framework/org.apache.http.legacy.boot.jar*2011144328:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk*1484444411:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes2.dex*1426535757:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes3.dex*34143081:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes4.dex*8585302:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes5.dex*3434078397:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes6.dex*3150739880:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes7.dex*3900420456:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes8.dex*814505103:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes9.dex*958008571:/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/ba
02-27 15:36:23.375 15464 15464 W o.va.exposed:p: Found duplicate classes, falling back to extracting from APK : /data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk
02-27 15:36:23.375 15464 15464 W o.va.exposed:p: NOTE: This wastes RAM and hurts startup performance.
02-27 15:36:23.375 15464 15464 W o.va.exposed:p: Found duplicated class when checking oat files: 'LMTT/ThirdAppInfoNew;' in /data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes8.dex and /data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/base.apk!classes8.dex
02-27 15:36:23.375 15464 15464 W o.va.exposed:p:
02-27 15:36:23.379 13684 13684 I RecentsModel: onTaskStackChanged# mTaskChangeId=28
02-27 15:36:23.552 15464 15491 I DpmTcmClient: RegisterTcmMonitor from: com.android.okhttp.TcmIdleTimerMonitor
02-27 15:36:23.554   662 15499 I netd    : ;; res_nquery(e.crashlytics.com, 1, 1)
02-27 15:36:24.589   662 15501 I netd    : ;; res_nquery(reports.crashlytics.com, 1, 1)
02-27 15:36:25.167   736  4196 E soundtrigger: audio_extn_sound_trigger_update_stream_status: invalid input device 0x0, for event 2
02-27 15:36:25.167   736  4196 E audio_hw_primary: disable_snd_device snd_device =2 device_name =speaker
02-27 15:36:25.167   736  4196 I soundtrigger: audio_extn_sound_trigger_update_device_status: device 0x2 of type 0 for Event 0, with Raise=0
02-27 15:36:25.545 15464 15464 W o.va.exposed:p: JIT profile information will not be recorded: profile file does not exits.
02-27 15:36:25.545 15464 15464 W o.va.exposed:p: JIT profile information will not be recorded: profile file does not exits.
02-27 15:36:25.597 15464 15464 E ActivityThread: Failed to find provider info for com.tencent.mm.coolassist.debugprovider
02-27 15:36:25.602 15464 15464 I o.va.exposed:p: Thread[1,tid=15464,Native,Thread*=0xf27c8000,peer=0x75263550,"main"] recursive attempt to load library "/data/user/0/io.va.exposed/virtual/data/app/com.tencent.mm/lib/libmmkv.so"
02-27 15:36:25.602 15464 15464 I MMKV    : page size:4096
02-27 15:36:25.602 15464 15464 I MMKV    : root dir: /data/user/0/io.va.exposed/virtual/data/user/0/com.tencent.mm/files/mmkv
02-27 15:36:25.603 15464 15464 I MMKV    : loading [prm_DeviceInfo_86400000] with 0 size in total, file size is 4096
02-27 15:36:25.603 15464 15464 I MMKV    : loaded [prm_DeviceInfo_86400000] with 0 values
02-27 15:36:25.603 15464 15464 I MMKV    : loading [MULTIPROCESSMMKV_PERSERVED_NAME] with 27 size in total, file size is 4096
02-27 15:36:25.603 15464 15464 I MMKV    : loading [MULTIPROCESSMMKV_PERSERVED_NAME] with crc 676271853 sequence 2
02-27 15:36:25.603 15464 15464 I MMKV    : loaded [MULTIPROCESSMMKV_PERSERVED_NAME] with 1 values
02-27 15:36:25.643 15464 15497 I CrashlyticsCore: Crashlytics report upload complete: 5C763DC30028-0001-3B82-2BA08157CEBD
02-27 15:36:25.718 15464 15511 I FA      : App measurement is starting up, version: 12451
02-27 15:36:25.718 15464 15511 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
02-27 15:36:25.718 15464 15511 I FA      : To enable faster debug mode event logging run:
02-27 15:36:25.718 15464 15511 I FA      :   adb shell setprop debug.firebase.analytics.app com.tencent.mm
02-27 15:36:25.743 15464 15464 W jni crash monitor: JNI_OnLoad
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager: Static environment:
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager:   extCache => /storage/emulated/0/Android/data/com.tencent.mm/cache
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager:   data => /data/user/0/io.va.exposed/virtual/data/user/0/com.tencent.mm
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager:   extData => /storage/emulated/0/Android/data/com.tencent.mm
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager:   storage => /storage/emulated/0
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager:   dataCache => /data/user/0/io.va.exposed/virtual/data/user/0/com.tencent.mm/cache
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager: File system configuration changed:
02-27 15:36:25.879 15464 15464 I VFS.FileSystemManager: [CLEAN ALL]
02-27 15:36:25.916 15464 15517 I WCDB    : Initialize JNI module (1/11) CursorWindow...
02-27 15:36:25.916 15464 15517 I WCDB    : Initialize JNI module (2/11) FileUtils...
02-27 15:36:25.916 15464 15517 I WCDB    : Initialize JNI module (3/11) ChunkedCursorWindow...
02-27 15:36:25.916 15464 15517 I WCDB    : Initialize JNI module (4/11) SQLiteConnection...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (5/11) SQLiteDebug...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (6/11) SQLiteDirectCursor...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (7/11) SQLiteGlobal...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (8/11) DBBackup...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (9/11) DBDumpUtil...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (10/11) DBRepair...
02-27 15:36:25.917 15464 15517 I WCDB    : Initialize JNI module (11/11) Log...
02-27 15:36:25.924 15464 15532 W HARDCODER: [LocalSocket.h,uninit:217]"uninit, pipe:[0,0], m_fd:0, queue:0, flag:1"
02-27 15:36:25.924 15464 15532 W HARDCODER: [LocalSocket.h,createSocket:312]"createSocket, connect socket, ret:-1, local:com.tencent.mm.hardcoder.client.sock, remote:oiface"
02-27 15:36:25.924 15464 15532 E HARDCODER: [LocalSocket.h,createSocket:335]"createSocket, connect failed ret:-1 fd:96 path:oiface"
02-27 15:36:25.924 15464 15532 W HARDCODER: [LocalSocket.h,uninit:217]"uninit, pipe:[94,95], m_fd:0, queue:0, flag:0"
02-27 15:36:25.991 15464 15517 E o.va.exposed:p: No implementation found for java.util.ArrayList com.tencent.mars.smc.SmcLogic.getLoadLibraries() (tried Java_com_tencent_mars_smc_SmcLogic_getLoadLibraries and Java_com_tencent_mars_smc_SmcLogic_getLoadLibraries__)
02-27 15:36:26.333 15464 15464 I TransactionHandlerProxy: rebound application, return
02-27 15:36:26.462 15464 15464 I TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@7355c97
02-27 15:36:26.462 15464 15464 I TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@7355c97
02-27 15:36:26.471 15464 15511 I FA      : Tag Manager is not found and thus will not be used
02-27 15:36:26.519 15464 15564 I Adreno  : QUALCOMM build                   : 4c638fb, I557c585805
02-27 15:36:26.519 15464 15564 I Adreno  : Build Date                       : 10/06/18
02-27 15:36:26.519 15464 15564 I Adreno  : OpenGL ES Shader Compiler Version: EV031.25.03.01
02-27 15:36:26.519 15464 15564 I Adreno  : Local Branch                     :
02-27 15:36:26.519 15464 15564 I Adreno  : Remote Branch                    :
02-27 15:36:26.519 15464 15564 I Adreno  : Remote Branch                    :
02-27 15:36:26.519 15464 15564 I Adreno  : Reconstruct Branch               :
02-27 15:36:26.519 15464 15564 I Adreno  : Build Config                     : S L 6.0.7 AArch32
02-27 15:36:26.522 15464 15564 I Adreno  : PFP: 0x005ff112, ME: 0x005ff066
--------- beginning of crash
02-27 15:36:26.523 15464 15464 E AndroidRuntime: FATAL EXCEPTION: main
02-27 15:36:26.523 15464 15464 E AndroidRuntime: Process: com.tencent.mm, PID: 15464
02-27 15:36:26.523 15464 15464 E AndroidRuntime: java.lang.SecurityException: Unknown calling package name 'com.tencent.mm'.
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at android.os.Parcel.createException(Parcel.java:1950)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1918)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1868)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source:41)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:82)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(Unknown Source:15)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$PostServiceBindingCallback.handleServiceSuccess(
Unknown Source:6)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:46)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:2)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source:46)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:275)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6863)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
02-27 15:36:26.523 15464 15464 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-27 15:36:26.526 15464 15564 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
02-27 15:36:26.526 15464 15564 I ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
02-27 15:36:26.526 15464 15464 I XApp    : uncaught :Thread[main,5,main]
02-27 15:36:26.526 15464 15464 I XApp    : java.lang.SecurityException: Unknown calling package name 'com.tencent.mm'.
02-27 15:36:26.526 15464 15464 I XApp    :      at android.os.Parcel.createException(Parcel.java:1950)
02-27 15:36:26.526 15464 15464 I XApp    :      at android.os.Parcel.readException(Parcel.java:1918)
02-27 15:36:26.526 15464 15464 I XApp    :      at android.os.Parcel.readException(Parcel.java:1868)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.IGmsServiceBroker$Stub$zza.getService(Unknown Source:41)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient.getRemoteService(Unknown Source:82)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient$LegacyClientCallbackAdapter.onReportServiceBinding(Unknown Source:15)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient$PostServiceBindingCallback.handleServiceSuccess(UnknownSource:6)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:46)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient$zza.deliverCallback(Unknown Source:2)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient$CallbackProxy.deliverCallback(Unknown Source:46)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.google.android.gms.common.internal.BaseGmsClient$zzb.handleMessage(Unknown Source:275)
02-27 15:36:26.526 15464 15464 I XApp    :      at android.os.Handler.dispatchMessage(Handler.java:106)
02-27 15:36:26.526 15464 15464 I XApp    :      at android.os.Looper.loop(Looper.java:193)
02-27 15:36:26.526 15464 15464 I XApp    :      at android.app.ActivityThread.main(ActivityThread.java:6863)
02-27 15:36:26.526 15464 15464 I XApp    :      at java.lang.reflect.Method.invoke(Native Method)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
02-27 15:36:26.526 15464 15464 I XApp    :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
02-27 15:36:26.527 15464 15564 I OpenGLRenderer: Initialized EGL, version 1.4
02-27 15:36:26.537 15464 15464 I o.va.exposed:p: System.exit called, status: 0
02-27 15:36:26.537 15464 15464 I AndroidRuntime: VM exiting with result code 0, cleanup skipped.
02-27 15:36:26.556   913   913 W thermal-engine: type=1400 audit(0.0:830): avc: denied { read } for name="u:object_r:system_prop:s0" dev="tmpfs" ino=21558 scontext=u:r:thermal-engine:s0 tcontext=u:object_r:system_prop:s0 tclass=file permissive=0
02-27 15:36:26.559  1367  2315 W InputDispatcher: channel 'e1630f6 com.tencent.mm/com.tencent.mm.ui.LauncherUI (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-27 15:36:26.559  1367  2315 E InputDispatcher: channel 'e1630f6 com.tencent.mm/com.tencent.mm.ui.LauncherUI (server)' ~ Channel is unrecoverably broken and will be disposed!
02-27 15:36:26.561  1367  2369 I WindowManager: WIN DEATH: Window{e1630f6 u0 com.tencent.mm/com.tencent.mm.ui.LauncherUI}
02-27 15:36:26.562  1367  2369 W InputDispatcher: Attempted to unregister already unregistered input channel 'e1630f6 com.tencent.mm/com.tencent.mm.ui.LauncherUI (server)'
02-27 15:36:26.562  1367  3588 I ActivityManager: Process io.va.exposed:p2 (pid 15464) has died: fore TOP
02-27 15:36:26.562  1367  1403 W libprocessgroup: kill(-15464, 9) failed: No such process
02-27 15:36:26.563  1367  3588 W ActivityManager: Force removing ActivityRecord{4a4266c u0 io.va.exposed/com.lody.virtual.client.stub.StubActivity$C2 t33479}: app died, no saved state
02-27 15:36:26.566   664   664 I Zygote  : Process 15464 exited cleanly (0)
02-27 15:36:26.571   913  1024 E libc    : Access denied finding property "sys.thermal.para"
02-27 15:36:26.595  1367  1403 W libprocessgroup: kill(-15464, 9) failed: No such process
02-27 15:36:26.595  1367  1403 I libprocessgroup: Successfully killed process cgroup uid 10324 pid 15464 in 32ms
02-27 15:36:26.606  1367  3588 E ActivityTrigger: activityResumeTrigger: not whiteListedcom.microsoft.launcher/com.microsoft.launcher.Launcher/48017
02-27 15:36:26.627  1367  1415 W ActivityManager: setHasOverlayUi called on unknown pid: 15464
02-27 15:36:26.633  1367  2369 W AlarmManager: Suspiciously short interval 10000 millis; expanding to 60 seconds
02-27 15:36:26.677 13684 13684 I RecentsModel: onTaskStackChanged# mTaskChangeId=29
02-27 15:36:27.119  1367  1367 I OIMC    : notified , mode GameMode changeTo 2
02-27 15:36:27.119  1367  2321 I OIMC    : The mode: GameMode is not entered
02-27 15:36:27.122  1367  1367 I OIMC    : notified , mode ReadMode changeTo 2
02-27 15:36:27.122  1367  2321 I OIMC    : The mode: ReadMode is not entered
02-27 15:36:27.200   796   901 W SurfaceFlinger: Attempting to set client state on removed layer: io.va.exposed/io.virtualapp.home.LoadingActivity#0
02-27 15:36:27.200   796   901 W SurfaceFlinger: Attempting to set client state on removed layer: io.va.exposed/io.virtualapp.home.NewHomeActivity#0
02-27 15:36:27.200   796   901 W SurfaceFlinger: Attempting to destroy on removed layer: io.va.exposed/io.virtualapp.home.LoadingActivity#0
02-27 15:36:27.200   796   901 W SurfaceFlinger: Attempting to destroy on removed layer: io.va.exposed/io.virtualapp.home.NewHomeActivity#0
02-27 15:36:27.206   796  3102 W SurfaceFlinger: Attempting to destroy on removed layer: Task=33478#0
02-27 15:36:27.595  1367  1376 I system_server: NativeAlloc concurrent copying GC freed 97886(5MB) AllocSpace objects, 36(1008KB) LOS objects, 41% free, 33MB/57MB, paused 157us total 170.732ms
02-27 15:36:27.616  1367  1374 W System  : A resource failed to call close.
02-27 15:36:28.303   662 15575 I netd    : ;; res_nquery(e.crashlytics.com, 1, 1)
02-27 15:36:28.559  2465  2465 E ndroid.systemu: Invalid ID 0x00000000.

**Comment by ChenSee** [comment]
+1
