### ISSUE TITLE
Installed App inside VirtualXposed Crashes on Android Q

### ISSUE THREAD

**Issue by cacorot** [android-hacker/VAExposed#564]
**Describe the bug**
Permission Denial: starting Intent { cmp=com.*/*Activity (has extras) } from ProcessRecord{f38b7fa 13895...:p1/u0a196} (pid=13895, uid=10196) not exported from uid 10143

**To Reproduce**
1. Install any app
2. Click the app
3. crashes

**Expected behavior**
Run successfully

**Smartphone (please complete the following information):**
 - Device: [Pixel2]
 - OS: [Android Q]
 - Version [Newest Code]

**Comment by tiann** [comment]
should be fixed in https://github.com/android-hacker/VirtualXposed/commit/b8ea12c3d74d6daaa938eb4205d88c67336a45bf

**Comment by cacorot** [comment]
yes, the installation issue has been addressed. But when I try to open 'skype' or 'outlook', they would not run normally.

**Comment by cacorot** [comment]
2019-03-20 12:05:16.707 22635-22635/? E/uncaught: java.lang.SecurityException: Permission Denial: starting Intent { cmp=com.skype.rover/com.skype.android.app.signin.unified.UnifiedLandingPageActivity } from ProcessRecord{ede3f90 22635:io.virtualapp.ex:p1/u0a204} (pid=22635, uid=10204) not exported from uid 10187
        at android.os.Parcel.createException(Parcel.java:2059)
        at android.os.Parcel.readException(Parcel.java:2027)
        at android.os.Parcel.readException(Parcel.java:1977)
        at android.app.IActivityTaskManager$Stub$Proxy.startActivity(IActivityTaskManager.java:3748)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1701)
        at android.app.Activity.startActivityForResult(Activity.java:5054)
        at android.app.Activity.startActivityForResult(Activity.java:5012)
        at android.support.v4.app.FragmentActivity.startActivityForResult(SourceFile:843)
        at android.app.Activity.startActivity(Activity.java:5383)
        at android.app.Activity.startActivity(Activity.java:5351)
        at com.skype.android.app.Navigation.toLandingPage(SourceFile:1777)
        at com.skype.android.app.Navigation.toLandingPage(SourceFile:1544)
        at com.skype.android.app.Navigation.toLandingPage(SourceFile:1536)
        at com.skype.android.app.main.SplashActivity.startLandingPageActivity(SourceFile:248)
        at com.skype.android.app.main.SplashActivity.access$000(SourceFile:62)
        at com.skype.android.app.main.SplashActivity$2.onAnimationEnd(SourceFile:221)
        at android.animation.Animator$AnimatorListener.onAnimationEnd(Animator.java:554)
        at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1235)
        at android.animation.ValueAnimator.doAnimationFrame(ValueAnimator.java:1477)
        at android.animation.AnimationHandler.doAnimationFrame(AnimationHandler.java:146)
        at android.animation.AnimationHandler.access$100(AnimationHandler.java:37)
        at android.animation.AnimationHandler$1.doFrame(AnimationHandler.java:54)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:979)
        at android.view.Choreographer.doCallbacks(Choreographer.java:791)
        at android.view.Choreographer.doFrame(Choreographer.java:722)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:966)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.wm.ActivityStackSupervisor.checkStartAnyActivityPermission(ActivityStackSupervisor.java:1034)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:746)
        at com.android.server.wm.ActivityStarter.startActivity(ActivityStarter.java:570)
        at com.android.server.wm.ActivityStarter.startActivityMayWait(ActivityStarter.java:1242)
        at com.android.server.wm.ActivityStarter.execute(ActivityStarter.java:508)

**Comment by cacorot** [comment]
It seems we need to hook 'ActivityTaskManager'

**Comment by cacorot** [comment]
Besides. there are problems of ContenService hooking. 
Please take a look at NotifyChange.
It should be like this:
            _**int sdkVersionIndex;
            if(BuildCompat.isQ()) {
                sdkVersionIndex = length - 2;
            } else {
                sdkVersionIndex = length - 1;
            }
            Object obj = args[sdkVersionIndex];
            if (obj != null && obj.getClass() == Integer.class) {
                if ((int) obj == targetSdkVersion) {
                    index = sdkVersionIndex;
                }
            }**_

**Comment by CarlosPue** [comment]
Si el virtualxposed esta presentando fallas al ingresar en el...

Cuando se hara la nueva actualizacion del virtualxposed mod
Para los videos juegos que actualizaron con un anti hacker...
