### ISSUE TITLE
红米Note7 升级MIUI10.3后无法打开软件

### ISSUE THREAD

**Issue by hongwanli** [android-hacker/VAExposed#598]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
红米Note7 升级MIUI10.3后无法打开VirtualXposed，打开直接闪退 

## 复现步骤

MIUI10.3 打开软件毕现

## 环境

机型：红米Note7
系统版本：安卓9.0
ROM版本：MIUI10.3稳定版
Xposed 插件以及插件版本：
VirtualXposed版本：0.17.3

## 补充

怀疑是MIUI10,3优化了某些东西导致的该问题

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by ahkudong** [comment]
Me too

**Comment by lvjianling** [comment]
me too.....

**Comment by lvjianling** [comment]
补充一下闪退之后的异常信息：
2019-04-14 10:47:24.625 2957-2957/? E/Fabric: Failure onPreExecute()
    java.lang.NullPointerException: Attempt to invoke interface method 'android.content.pm.PackageInfo com.lody.virtual.server.IPackageManager.getPackageInfo(java.lang.String, int, int)' on a null object reference
        at com.lody.virtual.client.ipc.VPackageManager.getPackageInfo(VPackageManager.java:86)
        at com.lody.virtual.client.hook.proxies.pm.MethodProxies$GetPackageInfo.call(MethodProxies.java:637)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:186)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy4.getPackageInfo(Unknown Source)
        at android.app.ApplicationPackageManager.getPackageInfoAsUser(ApplicationPackageManager.java:175)
        at android.app.ApplicationPackageManager.getPackageInfo(ApplicationPackageManager.java:153)
        at io.fabric.sdk.android.Onboarding.onPreExecute(Onboarding.java:78)
        at io.fabric.sdk.android.InitializationTask.onPreExecute(InitializationTask.java:44)
        at io.fabric.sdk.android.services.concurrency.AsyncTask.executeOnExecutor(AsyncTask.java:611)
        at io.fabric.sdk.android.services.concurrency.PriorityAsyncTask.executeOnExecutor(PriorityAsyncTask.java:43)
        at io.fabric.sdk.android.Kit.initialize(Kit.java:69)
        at io.fabric.sdk.android.Fabric.initializeKits(Fabric.java:421)
        at io.fabric.sdk.android.Fabric.init(Fabric.java:384)
        at io.fabric.sdk.android.Fabric.setFabric(Fabric.java:342)
        at io.fabric.sdk.android.Fabric.with(Fabric.java:313)
        at io.virtualapp.delegate.MyVirtualInitializer.onVirtualProcess(MyVirtualInitializer.java:29)
        at com.lody.virtual.client.core.VirtualCore.initialize(VirtualCore.java:236)
        at io.virtualapp.XApp.onCreate(XApp.java:48)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5949)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by hungxin** [comment]
me too

**Comment by lvjianling** [comment]
希望大神，早点帮我们解决一下这个问题，大神有时间帮适配一下小米J,,,B新的MIUI系统，，，

**Comment by ttting** [comment]
+1 希望处理下哦。

**Comment by zlroy1023** [comment]
同样遇到这个问题，希望大神可以看一看哈

**Comment by tianxiayu007** [comment]
me too,my phone is mi 9se

**Comment by gitskystar** [comment]
me too , mi8SE

**Comment by XiaoPanPanKevinPan** [comment]
红米note 6 pro也是
补充一下
版本0.7.3还能正常进入主画面
其后的版本皆是最多进入到背景黑色，下方有VirtualXposed字样的画面，接着就退出了

**Comment by FXTi** [comment]
红米K20 pro也是
@XiaoPanPanKevinPan 一样的状况，希望能够尽快修复，或者提出技术方案方便提交PR

**Comment by wanghui096** [comment]
米9一样的问题。

**Comment by cheese-p** [comment]
+1

**Comment by Mehedi4578** [comment]
Me too. Please Fix This Problem.

**Comment by YanzhaoLi** [comment]
Me too on K20Pro. Please Fix this problem

**Comment by felipevlk** [comment]
Me too fix please

**Comment by tiann** [comment]
Should be fixed long time ago in commit: https://github.com/android-hacker/VirtualXposed/commit/f8c5d7a143acb678a8b15848112b35ce49a0c4b5 

I made a new release today: https://github.com/android-hacker/VirtualXposed/releases/tag/0.17.4
