### ISSUE TITLE
9.0闪退是解决了，但xposed不能使用的问题没解决

### ISSUE THREAD

**Issue by weimingjue** [android-hacker/VAExposed#641]
**BUG反馈请不要用这个模版，否则直接关闭！！**

## 场景描述
红米not7pro，android系统9.0
xposed无法使用，点击”xposed install“无法打开，没有任何报错的日志
(请详细和精确地表述你的使用场景)

## 希望的解决方案

(你希望如何解决这个问题？)

## 其他信息

(其他你认为有用的信息)

**Comment by weimingjue** [comment]
原来我看错地方了，日志显示epic匹配不到对应的型号

05-31 16:08:34.229 23373-23373/de.robv.android.xposed.installer E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.robv.android.xposed.installer, PID: 23373
    java.lang.ExceptionInInitializerError
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:87)
        at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:144)
        at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:183)
        at me.weishu.exposed.ExposedBridge.initForXposedInstaller(ExposedBridge.java:239)
        at me.weishu.exposed.ExposedBridge.initOnce(ExposedBridge.java:84)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:333)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:214)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:209)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:149)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:146)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6823)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.RuntimeException: Do not support this ARCH now!! API LEVEL:28
        at me.weishu.epic.art.Epic.<clinit>(Epic.java:77)
        at me.weishu.epic.art.Epic.hookMethod(Epic.java:87) 
        at com.taobao.android.dexposed.DexposedBridge.hookMethod(DexposedBridge.java:144) 
        at com.taobao.android.dexposed.DexposedBridge.findAndHookMethod(DexposedBridge.java:183) 
        at me.weishu.exposed.ExposedBridge.initForXposedInstaller(ExposedBridge.java:239) 
        at me.weishu.exposed.ExposedBridge.initOnce(ExposedBridge.java:84) 
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:333) 
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:214) 
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:209) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:149) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:146) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6823) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
