### ISSUE TITLE
google play login failed

### ISSUE THREAD

**Issue by MrCWei** [android-hacker/VAExposed#749]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述

  android 9.0中登录google play商店会在com.google.android.gms.ui进程中发生crash，并停止登录

## 复现步骤

该问题是必现的，首先在设置中添加应用，选取并安装google play services 和 google play 商店，安装完成后，启动google play商店，此时提示登录，点击登录后就出现上述所说的crash

## 环境

机型：one plus 6t和sansumg Galaxy S9
系统版本：android 9.0
ROM版本：H2OS 9.0.17稳定版、One UI1.0稳定版
Xposed 插件以及插件版本：xposed installer 3.1.5，默认设置没启用插件
VirtualXposed版本：0.18.0

## 补充
下面是崩溃的log日志：

2019-11-15 19:19:37.631 29311-29311/com.google.android.gms.ui W/DynamiteModule: Local module descriptor class for providerinstaller not found.
2019-11-15 19:19:37.633 29311-29311/com.google.android.gms.ui W/ProviderHelper: Unknown dynamite feature providerinstaller
2019-11-15 19:19:37.633 29311-29311/com.google.android.gms.ui I/DynamiteModule: Considering local module providerinstaller:0 and remote module providerinstaller:0
2019-11-15 19:19:37.633 29311-29311/com.google.android.gms.ui W/ProviderInstaller: Failed to load providerinstaller module: No acceptable module found. Local version is 0 and remote version is 0.
2019-11-15 19:19:37.640 29311-29311/com.google.android.gms.ui V/NativeCrypto: Registering com/google/android/gms/org/conscrypt/NativeCrypto's 286 native methods...
2019-11-15 19:19:37.704 29311-29311/com.google.android.gms.ui I/ProviderInstaller: Installed default security provider GmsCore_OpenSSL
2019-11-15 19:19:37.714 29311-29311/com.google.android.gms.ui I/Safeboot: Checking safeboot...
2019-11-15 19:19:37.714 29311-29311/com.google.android.gms.ui I/Safeboot: Not entering safeboot; wrong process.
2019-11-15 19:19:37.761 29311-29311/com.google.android.gms.ui W/Primes: Primes not initialized, returning default (no-op) Primes instance which will ignore all calls. Please call Primes.initialize(...) before using any Primes API.
2019-11-15 19:19:37.761 29311-29311/com.google.android.gms.ui E/chenwb: bindApplicationNoCheck:dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk", zip file "/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk"],nativeLibraryDirectories=[/data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/lib, /data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk!/lib/armeabi-v7a, /data/user/0/io.va.exposed/virtual/data/app/com.google.android.gms/base.apk!/lib/armeabi-v7a, /system/lib]]]
2019-11-15 19:19:37.779 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@cfde552
2019-11-15 19:19:37.779 29311-29311/com.google.android.gms.ui W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cfde552
2019-11-15 19:19:37.779 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@cfde552
2019-11-15 19:19:37.779 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@cfde552
2019-11-15 19:19:37.921 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@cfde552
2019-11-15 19:19:37.926 29311-29311/com.google.android.gms.ui I/chatty: uid=11069(io.va.exposed) com.google.android.gms.ui identical 2 lines
2019-11-15 19:19:37.927 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@cfde552
2019-11-15 19:19:38.003 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@404126f
2019-11-15 19:19:38.003 29311-29311/com.google.android.gms.ui W/ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@404126f
2019-11-15 19:19:38.003 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@404126f
2019-11-15 19:19:38.008 29311-29311/com.google.android.gms.ui I/TransactionHandlerProxy: getActivityClient : android.os.BinderProxy@404126f
2019-11-15 19:19:38.046 29311-29311/com.google.android.gms.ui E/AppInstrumentation: activity crashed when call onCreate, clearing
2019-11-15 19:19:38.058 29311-29311/com.google.android.gms.ui D/AndroidRuntime: Shutting down VM
2019-11-15 19:19:38.061 29311-29311/com.google.android.gms.ui E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gms.ui, PID: 29311
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.auth.uiflows.addaccount.AccountIntroActivity}: java.lang.SecurityException: Neither user 11069 nor current process has android.permission.MANAGE_USERS.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:171)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.SecurityException: Neither user 11069 nor current process has android.permission.MANAGE_USERS.
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.getDeviceOwnerComponent(IDevicePolicyManager.java:6308)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy47.getDeviceOwnerComponent(Unknown Source)
        at android.app.admin.DevicePolicyManager.getDeviceOwnerComponentInner(DevicePolicyManager.java:5373)
        at android.app.admin.DevicePolicyManager.getDeviceOwnerComponentOnAnyUser(DevicePolicyManager.java:5356)
        at rzy.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):28)
        at rzy.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):39)
        at com.google.android.gms.auth.uiflows.addaccount.AddAccountController.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):129)
        at com.google.android.gms.auth.uiflows.addaccount.AccountIntroChimeraActivity.onCreate(:com.google.android.gms@19629030@19.6.29 (100408-278422107):55)
        at com.google.android.chimera.Activity.publicOnCreate(Unknown Source:0)
        at qst.onCreate(:com.google.android.gms@19629030@19.6.29 (100408-278422107):7)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:245)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:101)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:171) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6990) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:1924)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1952)
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceManageUsers(DevicePolicyManagerService.java:8885)
        at com.android.server.devicepolicy.DevicePolicyManagerService.getDeviceOwnerComponent(DevicePolicyManagerService.java:8141)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:1252)
2019-11-15 19:19:38.068 29311-29311/com.google.android.gms.ui I/XApp: uncaught :Thread[main,5,main]
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gms/com.google.android.gms.auth.uiflows.addaccount.AccountIntroActivity}: java.lang.SecurityException: Neither user 11069 nor current process has android.permission.MANAGE_USERS.
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3092)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:171)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:6990)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
     Caused by: java.lang.SecurityException: Neither user 11069 nor current process has android.permission.MANAGE_USERS.
        at android.os.Parcel.createException(Parcel.java:1966)
        at android.os.Parcel.readException(Parcel.java:1934)
        at android.os.Parcel.readException(Parcel.java:1884)
        at android.app.admin.IDevicePolicyManager$Stub$Proxy.getDeviceOwnerComponent(IDevicePolicyManager.java:6308)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy47.getDeviceOwnerComponent(Unknown Source)
        at android.app.admin.DevicePolicyManager.getDeviceOwnerComponentInner(DevicePolicyManager.java:5373)
        at android.app.admin.DevicePolicyManager.getDeviceOwnerComponentOnAnyUser(DevicePolicyManager.java:5356)
        at rzy.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):28)
        at rzy.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):39)
        at com.google.android.gms.auth.uiflows.addaccount.AddAccountController.a(:com.google.android.gms@19629030@19.6.29 (100408-278422107):129)
        at com.google.android.gms.auth.uiflows.addaccount.AccountIntroChimeraActivity.onCreate(:com.google.android.gms@19629030@19.6.29 (100408-278422107):55)
        at com.google.android.chimera.Activity.publicOnCreate(Unknown Source:0)
        at qst.onCreate(:com.google.android.gms@19629030@19.6.29 (100408-278422107):7)
        at android.app.Activity.performCreate(Activity.java:7326)
        at android.app.Activity.performCreate(Activity.java:7317)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callActivityOnCreate(InstrumentationDelegate.java:245)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callActivityOnCreate(AppInstrumentation.java:101)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:171) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:6990) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445) 
     Caused by: android.os.RemoteException: Remote stack trace:
        at android.app.ContextImpl.enforce(ContextImpl.java:1924)
        at android.app.ContextImpl.enforceCallingOrSelfPermission(ContextImpl.java:1952)
        at com.android.server.devicepolicy.DevicePolicyManagerService.enforceManageUsers(DevicePolicyManagerService.java:8885)
        at com.android.server.devicepolicy.DevicePolicyManagerService.getDeviceOwnerComponent(DevicePolicyManagerService.java:8141)
        at android.app.admin.IDevicePolicyManager$Stub.onTransact(IDevicePolicyManager.java:1252)
2019-11-15 19:19:38.078 29311-29311/com.google.android.gms.ui I/o.va.exposed:p: System.exit called, status: 0
2019-11-15 19:19:38.078 29311-29311/com.google.android.gms.ui I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.

**Comment by MrCWei** [comment]
都不回复的，直接就关了？

**Comment by tiann** [comment]
Out of date，有新问题重新提。
