### ISSUE TITLE
华为荣耀10青春版 微信打不开 Environment.getExternalStorageDirectory() 报错

### ISSUE THREAD

**Issue by zy990081568** [android-hacker/VAExposed#854]
**反馈BUG之前，先issue里面搜看看有没有别人已经反馈过，重复的不予处理！！**

## 问题描述
05-11 14:51:51.844 26837 26837 W System.err: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-11 14:51:51.844 26837 26837 W System.err: at android.os.Environment.getExternalStorageDirectory(Environment.java:5
87)
05-11 14:51:51.844 26837 26837 W System.err: at com.tencent.mm.loader.j.b.(SourceFile:38)
05-11 14:51:51.844 26837 26837 W System.err: ... 27 more
05-11 14:51:51.845 26837 26837 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang
.String android.content.Context.getPackageName()' on a null object reference
05-11 14:51:51.845 26837 26837 W System.err: at android.app.ActivityThread.installProvider(ActivityThread.java:7698)
05-11 14:51:51.845 26837 26837 W System.err: at java.lang.reflect.Method.invoke(Native Method)
05-11 14:51:51.845 26837 26837 W System.err: at mirror.RefMethod.call(RefMethod.java:63)
05-11 14:51:51.845 26837 26837 W System.err: at mirror.android.app.ActivityThread.installProvider(ActivityThread.java
:60)

系统有这个错误提示 

05-09 18:26:45.474 25848 25896 I HwApiCacheMangerEx: apicache getVolumeList uid is invalid -2
--

（请尽量详细地描述你遇到的问题）

## 复现步骤
 
（请分步骤描述如何复现这个BUG，非毕现BUG请给出如何能大概率复现的步骤）

## 环境

机型：畅享10青春版
系统版本：10.0.0.161
ROM版本：Android 10（请区分内测版和开发版稳定版，除稳定版本外不予修复）
Xposed 插件以及插件版本：
VirtualXposed版本：0.18.2

## 补充

（别的需要描述的内容）

**写完之后，请自己再读一遍自己写的，如果你自己都读不懂，就不用说修复了**

**Comment by zy990081568** [comment]
05-11 09:55:14.938 20543 20582 E AndroidRuntime: Process: com.tencent.mm, PID: 20543
05-11 09:55:14.938 20543 20582 E AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at android.os.Environment.getExternalStorageDirectory(Environmen
t.java:587)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at com.jiongbull.jlog.util.LogUtils.genDirPath(LogUtils.java:115
)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at com.jiongbull.jlog.util.PrinterUtils.printFile(PrinterUtils.j
ava:65)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at com.jiongbull.jlog.printer.DefaultPrinter.printFile(DefaultPr
inter.java:44)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at com.jiongbull.jlog.Logger.printLog(Logger.java:444)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at com.jiongbull.jlog.Logger.e(Logger.java:219)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at com.lody.virtual.helper.utils.Log$6.run(Log.java:129)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:888)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:100)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:213)
05-11 09:55:14.938 20543 20582 E AndroidRuntime:        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by zy990081568** [comment]
05-11 14:51:51.844 26837 26837 W System.err: Caused by: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
05-11 14:51:51.844 26837 26837 W System.err:    at android.os.Environment.getExternalStorageDirectory(Environment.java:5
87)
05-11 14:51:51.844 26837 26837 W System.err:    at com.tencent.mm.loader.j.b.<clinit>(SourceFile:38)
05-11 14:51:51.844 26837 26837 W System.err:    ... 27 more
05-11 14:51:51.845 26837 26837 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang
.String android.content.Context.getPackageName()' on a null object reference
05-11 14:51:51.845 26837 26837 W System.err:    at android.app.ActivityThread.installProvider(ActivityThread.java:7698)
05-11 14:51:51.845 26837 26837 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
05-11 14:51:51.845 26837 26837 W System.err:    at mirror.RefMethod.call(RefMethod.java:63)
05-11 14:51:51.845 26837 26837 W System.err:    at mirror.android.app.ActivityThread.installProvider(ActivityThread.java
:60)

**Comment by zy990081568** [comment]
再外部安装一个微信就没有这个问题了

**Comment by zy990081568** [comment]
已解决
