### ISSUE TITLE
微信登录需要滑块验证的时候，闪退返回至登录界面

### ISSUE THREAD

**Issue by Ayu8806** [android-hacker/VAExposed#858]
## 问题描述
微信登录输入账号密码，点击登录跳转至滑块验证界面，界面没有加载出来，直接返回至密码输入界面。

## 复现步骤
(新设备登录微信的时候，需要滑块验证和二次身份验证)
百分百复现
输入密码 点击登录就会出现，导致现在登录不进去。

## 环境

机型：华为荣耀8c
系统版本：EMUI 8.2.0
ROM版本：Android 8.1.0
Xposed 插件以及插件版本：xposed 90
VirtualXposed版本：0.18.1 /0.18.2

## 补充
1590486604.443 30498-30637/com.tencent.mm:tools W/System.err: java.lang.IllegalArgumentException: You cannot keep your settings in the secure settings.
1590486604.443 30498-30637/com.tencent.mm:tools W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:165)
1590486604.443 30498-30637/com.tencent.mm:tools W/System.err:     at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
1590486604.444 30498-30637/com.tencent.mm:tools W/System.err:     at android.content.ContentProviderProxy.call(ContentProviderNative.java:651)
1590486604.444 30498-30637/com.tencent.mm:tools W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
1590486604.444 30498-30637/com.tencent.mm:tools W/System.err:     at com.lody.virtual.client.hook.base.MethodBox.call(MethodBox.java:24)
1590486604.444 30498-30637/com.tencent.mm:tools W/System.err:     at com.lody.virtual.client.hook.providers.SettingsProviderHook.call(SettingsProviderHook.java:73)
1590486604.445 30498-30637/com.tencent.mm:tools W/System.err:     at com.lody.virtual.client.hook.providers.ProviderHook.invoke(ProviderHook.java:166)
1590486604.445 30498-30637/com.tencent.mm:tools W/System.err:     at java.lang.reflect.Proxy.invoke(Proxy.java:913)
1590486604.445 30498-30637/com.tencent.mm:tools W/System.err:     at $Proxy51.call(Unknown Source)
1590486604.445 30498-30637/com.tencent.mm:tools W/System.err:     at android.provider.Settings$NameValueCache.putStringForUser(Settings.java:1928)
1590486604.445 30498-30637/com.tencent.mm:tools W/System.err:     at android.provider.Settings$System.putStringForUser(Settings.java:2393)
1590486604.446 30498-30637/com.tencent.mm:tools W/System.err:     at android.provider.Settings$System.putString(Settings.java:2369)
1590486604.446 30498-30637/com.tencent.mm:tools W/System.err:     at com.tencent.tbs.common.baseinfo.GuidLoader.a(TbsJavaCore:268)
1590486604.446 30498-30637/com.tencent.mm:tools W/System.err:     at com.tencent.tbs.common.baseinfo.GuidLoader.b(TbsJavaCore:33)
1590486604.446 30498-30637/com.tencent.mm:tools W/System.err:     at com.tencent.tbs.common.baseinfo.GuidLoader$1.run(TbsJavaCore:190)
1590486604.447 30498-30637/com.tencent.mm:tools W/System.err:     at com.tencent.common.threadpool.MyThreadPoolExecutor.a(TbsJavaCore:1196)
1590486604.447 30498-30637/com.tencent.mm:tools W/System.err:     at com.tencent.common.threadpool.MyThreadPoolExecutor$a.run(TbsJavaCore:670)
1590486604.447 30498-30637/com.tencent.mm:tools W/System.err:     at java.lang.Thread.run(Thread.java:784)
1590486604.447 30498-30637/com.tencent.mm:tools W/System.err:     at com.tencent.common.threadpool.QBThreadFactory$1.run(TbsJavaCore:54)
1590486604.457 30498-30631/com.tencent.mm:tools W/System.err: java.io.EOFException
1590486604.457 30498-30631/com.tencent.mm:tools W/System.err:     at java.io.DataInputStream.readFully(DataInputStream.java:200)
1590486604.458 30498-30631/com.tencent.mm:tools W/System.err:     at java.io.DataInputStream.readUnsignedShort(DataInputStream.java:341)
1590486604.458 30498-30631/com.tencent.mm:tools W/System.err:     at java.io.DataInputStream.readUTF(DataInputStream.java:586)
1590486604.458 30498-30631/com.tencent.mm:tools W/System.err:     at java.io.DataInputStream.readUTF(DataInputStream.java:561)
1590486604.458 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.serverconfig.IPListDataManager.a(TbsJavaCore:142)
1590486604.459 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.serverconfig.IPListDataManager.getServerList(TbsJavaCore:471)
1590486604.459 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.serverconfig.IPListDataManager.getServerList(TbsJavaCore:513)
1590486604.459 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.serverconfig.a.a(TbsJavaCore:389)
1590486604.459 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.serverconfig.WupServerConfigsWrapper.needPullWupServer(TbsJavaCore:130)
1590486604.459 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.tbs.common.baseinfo.TbsWupManager.doMultiWupRequestForThirdParty(TbsJavaCore:395)
1590486604.460 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.tbs.common.baseinfo.TbsWupManager$1.run(TbsJavaCore:144)
1590486604.460 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.threadpool.MyThreadPoolExecutor.a(TbsJavaCore:1196)
1590486604.460 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.threadpool.MyThreadPoolExecutor$a.run(TbsJavaCore:670)
1590486604.461 30498-30631/com.tencent.mm:tools W/System.err:     at java.lang.Thread.run(Thread.java:784)
1590486604.461 30498-30631/com.tencent.mm:tools W/System.err:     at com.tencent.common.threadpool.QBThreadFactory$1.run(TbsJavaCore:54)
------------------------------------------------------------------------------------------------
2020-05-26 17:50:08.393 30498-30498/com.tencent.mm:tools E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.tencent.mm:tools, PID: 30498
    java.lang.SecurityException: Requesting code from com.tencent.mm to be run in process com.tencent.mm:tools/10003
        at android.app.ActivityThread.getPackageInfo(ActivityThread.java:2511)
        at android.app.ContextImpl.createPackageContextAsUser(ContextImpl.java:2288)
        at android.app.ContextImpl.createPackageContext(ContextImpl.java:2269)
        at android.app.ActivityThread.getContextForClassLoader(ActivityThread.java:7592)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7202)
        at android.app.ActivityThread.acquireProvider(ActivityThread.java:6819)
        at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:2824)
        at android.content.ContentResolver.acquireProvider(ContentResolver.java:1776)
        at android.content.ContentResolver.call(ContentResolver.java:1746)
        at com.tencent.mm.by.a.call(SourceFile:759)
        at com.tencent.mm.by.a.bjO(SourceFile:727)
        at com.tencent.mm.cb.f.dqN(SourceFile:120)
        at com.tencent.mm.cb.f.<init>(SourceFile:63)
        at com.tencent.mm.cb.f.dqL(SourceFile:71)
        at com.tencent.mm.cb.g.p(SourceFile:63)
        at com.tencent.mm.cb.g.o(SourceFile:35)
        at com.tencent.mm.plugin.emoji.PluginEmoji$2.h(SourceFile:104)
        at com.tencent.mm.ui.e.c.b.h(SourceFile:19)
        at com.tencent.mm.ui.q.dym(SourceFile:1600)
        at com.tencent.mm.ui.q.setMMTitle(SourceFile:1408)
        at com.tencent.mm.ui.MMActivity.setMMTitle(SourceFile:559)
        at com.tencent.mm.plugin.webview.ui.tools.WebViewUI.setMMTitle(SourceFile:1006)
        at com.tencent.mm.plugin.webview.ui.tools.WebViewUI$g.d(SourceFile:4122)
        at com.tencent.xweb.x5.k$1.onReceivedTitle(SourceFile:360)
        at com.tencent.smtt.sdk.q.onReceivedTitle(Unknown Source:15)
        at com.tencent.tbs.core.webkit.tencent.c.a(TbsJavaCore:59)
        at android.webview.chromium.WebViewContentsClientAdapter.e(TbsJavaCore:473)
        at android.webview.chromium.tencent.TencentWebViewContentsClientAdapter.e(TbsJavaCore:1356)
        at org.chromium.android_webview.f$e.handleMessage(TbsJavaCore:227)
        at android.os.Handler.dispatchMessage(Handler.java:109)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7555)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)

**Comment by jiachengliu** [comment]
换32位的微信

**Comment by tiann** [comment]
#815
