### ISSUE TITLE
io redirect failed.

### ISSUE THREAD

**Issue by sorosunrain** [android-hacker/VAExposed#895]
## 问题描述

升级手机系统后，VP不起作用了。

## 环境

机型：小米9
系统版本：Android 10, API 29
ROM版本：MIUI12 开发版公测
VirtualXposed版本：vxp分支代码

## 补充

D/NativeEngine: enableIORedirect: /data/app/io.va.exposed-HpxklGHg6p01RfEQ06ONIA==/lib/arm64/libva++
E/NativeEngine: java.lang.RuntimeException: io redirect failed.
        at com.lody.virtual.client.NativeEngine.enableIORedirect(NativeEngine.java:151)
        at com.lody.virtual.client.VClientImpl.startIOUniformer(VClientImpl.java:481)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:277)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:218)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:213)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:149)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2051)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:236)
        at android.app.ActivityThread.main(ActivityThread.java:7601)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by sorosunrain** [comment]
问题已解决：
VirtualCore.get().getContext().getApplicationInfo().nativeLibraryDir + File.separator + "lib" + LIB_NAME
VirtualCore.get().getContext().getApplicationInfo().nativeLibraryDir + File.separator + "lib" + LIB_NAME + ".so"
后面少个.so
