### ISSUE TITLE
Cannot log in Google account with microG

### ISSUE THREAD

**Issue by hangcidu** [android-hacker/VAExposed#939]
**Describe the bug**

When using the provided Google Service, cannot log in Google account in the microG service.

**To Reproduce**
1. Go to 'Advanced Settings' - 'Install/Uninstall Google Service', successfully install Google Service.
2. Login in the microG, after you have input the account and password, it will show "error when communicating with Google"

**Expected behavior**
The Google account should be usable.

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: K30 Pro Chinese mainland
 - OS: MIUI 12 based on Android 11

**Additional info**
I could use Google service outside VitualXposed.

**Comment by tiann** [comment]
some useful logs:

```txt
2020-11-26 18:29:55.044 25531-26530/? W/GmsAuthLoginBrowser: onException
    java.lang.SecurityException: uid 10378 cannot get secrets for accounts of type: com.google
        at android.os.Parcel.createException(Parcel.java:2074)
        at android.os.Parcel.readException(Parcel.java:2042)
        at android.os.Parcel.readException(Parcel.java:1990)
        at android.accounts.IAccountManager$Stub$Proxy.setAccountVisibility(IAccountManager.java:2596)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.lody.virtual.client.hook.base.MethodInvocationStub$HookInvocationHandler.invoke(MethodInvocationStub.java:189)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy21.setAccountVisibility(Unknown Source)
        at android.accounts.AccountManager.setAccountVisibility(AccountManager.java:1040)
        at org.microg.gms.auth.AuthManager.setPermitted(AuthManager.java:98)
        at org.microg.gms.auth.login.LoginActivity.retrieveGmsToken(LoginActivity.java:324)
        at org.microg.gms.auth.login.LoginActivity.access$500(LoginActivity.java:78)
        at org.microg.gms.auth.login.LoginActivity$2.onResponse(LoginActivity.java:298)
        at org.microg.gms.auth.login.LoginActivity$2.onResponse(LoginActivity.java:283)
        at org.microg.gms.common.HttpFormClient$1.run(HttpFormClient.java:198)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.accounts.AccountManagerService.setAccountVisibility(AccountManagerService.java:770)
        at android.accounts.IAccountManager$Stub.onTransact(IAccountManager.java:1255)
        at com.android.server.accounts.AccountManagerService.onTransact(AccountManagerService.java:1074)
        at android.os.Binder.execTransactInternal(Binder.java:1021)
        at android.os.Binder.execTransact(Binder.java:994)
```

**Comment by ghost** [comment]
return Mgr.setAccountVisibility((Account) objArr[0], (String) objArr[1], ((Integer) objArr[2]).intValue());

**Comment by ghost** [comment]
@tiann 
Minmin guard don't work
Press apply or toggle switch caused VXP crash 
VXP 0.20.2
