### ISSUE TITLE
一加8T-Android11-启动微信，bindApplicationNoCheck() 方法中 mInitialApplication 返回null，导致无法调用起微信

### ISSUE THREAD

**Issue by cannon-lz** [android-hacker/VAExposed#969]
## 问题描述

一加8T-Android11-启动微信，bindApplicationNoCheck() 方法中 mInitialApplication 返回null，导致无法调用起微信

Process: com.tencent.mm, PID: 2124
    java.lang.RuntimeException: Unable to create application  [null application] : java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:389)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:218)
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:213)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:160)
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:157)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:233)
        at android.app.ActivityThread.main(ActivityThread.java:7959)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Application.onCreate()' on a null object reference
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1208)
        at com.lody.virtual.client.hook.delegate.InstrumentationDelegate.callApplicationOnCreate(InstrumentationDelegate.java:225)
        at com.lody.virtual.client.hook.delegate.AppInstrumentation.callApplicationOnCreate(AppInstrumentation.java:176)
        at com.lody.virtual.client.VClientImpl.bindApplicationNoCheck(VClientImpl.java:373)
        at com.lody.virtual.client.VClientImpl.bindApplication(VClientImpl.java:218) 
        at com.lody.virtual.client.VClientImpl.bindApplicationForActivity(VClientImpl.java:213) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:160) 
        at android.app.TransactionHandlerProxy.handleLaunchActivity(TransactionHandlerProxy.java:157) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2198) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:233) 
        at android.app.ActivityThread.main(ActivityThread.java:7959) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978) 

## 复现步骤

1.使用一加8T（Android11）安装微信
2.打开微信，查看logcat

## 环境

机型：一加8T
系统版本：Android 11
ROM版本：Hydrogen OS 11.0.6.8.KB05
Xposed 插件以及插件版本：3.1.5
VirtualXposed版本：0.20.2

**Comment by tiann** [comment]
https://github.com/android-hacker/VirtualXposed/commit/317727b4a9d8db2cb7bf87e8292c6eaaee600733
